<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>marketing_campaign_eda</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="marketing_campaign_eda_files/libs/clipboard/clipboard.min.js"></script>
<script src="marketing_campaign_eda_files/libs/quarto-html/quarto.js"></script>
<script src="marketing_campaign_eda_files/libs/quarto-html/popper.min.js"></script>
<script src="marketing_campaign_eda_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="marketing_campaign_eda_files/libs/quarto-html/anchor.min.js"></script>
<link href="marketing_campaign_eda_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="marketing_campaign_eda_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="marketing_campaign_eda_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="marketing_campaign_eda_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="marketing_campaign_eda_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="beyond-the-ad-a-holistic-examination-of-e-commerce-variables-steering-marketing-responses" class="level1">
<h1>Beyond the Ad: A Holistic Examination of E-commerce Variables Steering Marketing Responses</h1>
<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p>In the evolving e-commerce landscape, the understanding of customer behavior has been recognized as paramount. A comprehensive analysis of marketing campaign data has been conducted to offer insights into the factors influencing customer responses to campaigns. The emphasis has been placed on variables such as spending habits, purchase recency, and website visit frequency. The findings have revealed:</p>
<ol type="1">
<li>A positive relationship between the frequency of web visits and a customer’s response was observed. However, this relationship has been nuanced by the total spending of the customer, emphasizing the necessity to approach customer behavior with a holistic perspective.</li>
<li>The diminishing effect of total spending with increased web visits suggests a complex interaction between engagement and expenditure.</li>
<li>A model, deemed reliable through metrics such as AIC, PCP, and Tjur’s R2, has been used to validate the insights.</li>
</ol>
<p>From a strategic viewpoint, businesses are advised not only to drive web traffic but also to ensure that these visits lead to meaningful engagements and purchases.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>The advent of the digital age has ushered in a renewed understanding of consumer behavior. As a significant majority of transactions have transitioned online, the need to discern what drives a customer to respond to a campaign or finalize a purchase has become paramount.</p>
<p>In this report, a detailed exploration into the intricacies of customer responses has been undertaken. Insights have been drawn from a comprehensive dataset that encapsulates various facets of customer behavior. Through the exploratory data analysis, influential factors have been highlighted, new perspectives on traditionally overlooked variables have been presented, and a nuanced relationship between website engagement and spending has been showcased.</p>
<p>As the report is navigated, the complexities of customer behavior, the interplay between various influential factors, and recommendations on how these insights can be harnessed by businesses for optimized marketing campaigns will be revealed.</p>
</section>
<section id="technical-setup" class="level2">
<h2 class="anchored" data-anchor-id="technical-setup">2. Technical Setup</h2>
<section id="python" class="level3">
<h3 class="anchored" data-anchor-id="python">Python</h3>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#data processing</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> datetime</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> functools</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> pointbiserialr</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.graph_objects <span class="im">as</span> go</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.figure_factory <span class="im">as</span> ff</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotly.subplots <span class="im">import</span> make_subplots</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="vs">r"D:\Project\rpy2_testing\src"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> my_utils</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="r" class="level3">
<h3 class="anchored" data-anchor-id="r">R</h3>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'R_HOME'</span>] <span class="op">=</span> <span class="st">'C:/Program Files/R/R-4.3.1'</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import rpy2's package module</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rpy2.robjects.packages <span class="im">import</span> importr</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> functools <span class="im">import</span> partial</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rpy2.robjects.packages <span class="im">as</span> rpackages</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rpy2.robjects.vectors <span class="im">import</span> StrVector</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rpy2.ipython <span class="im">import</span> html</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>html.html_rdataframe<span class="op">=</span>partial(html.html_rdataframe, table_class<span class="op">=</span><span class="st">"docutils"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RUn to install R packages if not installed yet</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>utils <span class="op">=</span> importr(<span class="st">'utils'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> importr(<span class="st">'base'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># select a mirror for R packages</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>utils.chooseCRANmirror(ind<span class="op">=</span><span class="dv">1</span>) <span class="co"># select the first mirror in the list</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># R package names</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>packnames <span class="op">=</span> (<span class="st">'peformance'</span>, <span class="st">'tidyr'</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Selectively install what needs to be install.</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>names_to_install <span class="op">=</span> [x <span class="cf">for</span> x <span class="kw">in</span> packnames <span class="cf">if</span> <span class="kw">not</span> rpackages.isinstalled(x)]</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(names_to_install) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    utils.install_packages(StrVector(names_to_install))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>load_ext rpy2.ipython</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>R</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>library(dplyr)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>library(ggplot2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>library(ggstatsplot)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>library(gridExtra)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>library(kableExtra)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>library(ggthemr)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>library(summarytools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-collection-understanding-and-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-collection-understanding-and-preparation">3. Data Collection, Understanding, and Preparation</h2>
<section id="data-collection" class="level3">
<h3 class="anchored" data-anchor-id="data-collection">3.1. Data Collection</h3>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_raw <span class="op">=</span> pd.read_csv(<span class="st">'data\marketing_campaign.csv'</span>, sep<span class="op">=</span><span class="st">'</span><span class="ch">\t</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-understanding" class="level3">
<h3 class="anchored" data-anchor-id="data-understanding">3.2. Data Understanding</h3>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>my_utils.dataframe_info(df_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Column</th>
      <th>Data Type</th>
      <th>Unique Count</th>
      <th>Unique Sample</th>
      <th>Missing Values</th>
      <th>Missing Percentage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>ID</td>
      <td>int64</td>
      <td>2240</td>
      <td>[5524, 2174, 4141, 6182, 5324]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Year_Birth</td>
      <td>int64</td>
      <td>59</td>
      <td>[1957, 1954, 1965, 1984, 1981]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Education</td>
      <td>object</td>
      <td>5</td>
      <td>[Graduation, PhD, Master, Basic, 2n Cycle]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Marital_Status</td>
      <td>object</td>
      <td>8</td>
      <td>[Single, Together, Married, Divorced, Widow]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Income</td>
      <td>float64</td>
      <td>1974</td>
      <td>[58138.0, 46344.0, 71613.0, 26646.0, 58293.0]</td>
      <td>24</td>
      <td>1.0714</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Kidhome</td>
      <td>int64</td>
      <td>3</td>
      <td>[0, 1, 2]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Teenhome</td>
      <td>int64</td>
      <td>3</td>
      <td>[0, 1, 2]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Dt_Customer</td>
      <td>object</td>
      <td>663</td>
      <td>[04-09-2012, 08-03-2014, 21-08-2013, 10-02-201...</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Recency</td>
      <td>int64</td>
      <td>100</td>
      <td>[58, 38, 26, 94, 16]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>9</th>
      <td>MntWines</td>
      <td>int64</td>
      <td>776</td>
      <td>[635, 11, 426, 173, 520]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>10</th>
      <td>MntFruits</td>
      <td>int64</td>
      <td>158</td>
      <td>[88, 1, 49, 4, 43]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>11</th>
      <td>MntMeatProducts</td>
      <td>int64</td>
      <td>558</td>
      <td>[546, 6, 127, 20, 118]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>12</th>
      <td>MntFishProducts</td>
      <td>int64</td>
      <td>182</td>
      <td>[172, 2, 111, 10, 46]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>13</th>
      <td>MntSweetProducts</td>
      <td>int64</td>
      <td>177</td>
      <td>[88, 1, 21, 3, 27]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>14</th>
      <td>MntGoldProds</td>
      <td>int64</td>
      <td>213</td>
      <td>[88, 6, 42, 5, 15]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>15</th>
      <td>NumDealsPurchases</td>
      <td>int64</td>
      <td>15</td>
      <td>[3, 2, 1, 5, 4]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>16</th>
      <td>NumWebPurchases</td>
      <td>int64</td>
      <td>15</td>
      <td>[8, 1, 2, 5, 6]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>17</th>
      <td>NumCatalogPurchases</td>
      <td>int64</td>
      <td>14</td>
      <td>[10, 1, 2, 0, 3]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>18</th>
      <td>NumStorePurchases</td>
      <td>int64</td>
      <td>14</td>
      <td>[4, 2, 10, 6, 7]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>19</th>
      <td>NumWebVisitsMonth</td>
      <td>int64</td>
      <td>16</td>
      <td>[7, 5, 4, 6, 8]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>20</th>
      <td>AcceptedCmp3</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>21</th>
      <td>AcceptedCmp4</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>22</th>
      <td>AcceptedCmp5</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>23</th>
      <td>AcceptedCmp1</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>24</th>
      <td>AcceptedCmp2</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Complain</td>
      <td>int64</td>
      <td>2</td>
      <td>[0, 1]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Z_CostContact</td>
      <td>int64</td>
      <td>1</td>
      <td>[3]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Z_Revenue</td>
      <td>int64</td>
      <td>1</td>
      <td>[11]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Response</td>
      <td>int64</td>
      <td>2</td>
      <td>[1, 0]</td>
      <td>0</td>
      <td>0.0000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>This dataset contains 29 variables, consisting of integers (int64), floating points (float64), and objects (object).</p>
<ul>
<li><p><strong>ID</strong>: A unique identifier for each customer. This feature may not contribute to a predictive model.</p></li>
<li><p><strong>Year_Birth</strong>: The birth year of customers, which can be converted to ‘Age’.</p></li>
<li><p><strong>Education</strong> and <strong>Marital_Status</strong>: Categorical features that may require one-hot encoding.</p></li>
<li><p><strong>Income</strong>: A continuous feature indicating customer’s income, with some missing values that need to be filled.</p></li>
<li><p><strong>Kidhome</strong> and <strong>Teenhome</strong>: Integer variables indicating the number of children in the household.</p></li>
<li><p><strong>Dt_Customer</strong>: The joining date of customers, which may need to be converted to ‘tenure’ or similar measure.</p></li>
<li><p><strong>Recency</strong>: Indicates how recently a customer made a purchase. Further context is needed for proper interpretation.</p></li>
<li><p><strong>MntX</strong> and <strong>NumXPurchases</strong>: Represent the amount spent on different categories of products and the number of purchases made through different channels, respectively.</p></li>
<li><p><strong>AcceptedCmpX</strong>: Binary features indicating whether the customer accepted offers in different campaigns.</p></li>
<li><p><strong>Complain</strong>: A binary feature indicating if the customer made a complaint recently.</p></li>
<li><p><strong>Z_CostContact</strong> and <strong>Z_Revenue</strong>: Features with no variance, hence can be removed.</p></li>
<li><p><strong>Response</strong>: The binary target variable indicating whether a customer accepted the latest offer.</p></li>
</ul>
<p>Preprocessing will depend on the final model chosen and can involve scaling, encoding, or dropping some features.</p>
</section>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">3.2. Data Preparation</h3>
<p>This phase of the data analysis project focuses on enhancing the quality of the dataset for further stages, which include exploratory data analysis, model building, and interpretation.</p>
<p>Notes on processing that need to be done are as follows:</p>
<ol type="1">
<li><p><strong>Removal of Unnecessary Features</strong>: Features such as ‘ID’, ‘Z_CostContact’, and ‘Z_Revenue’, which do not contribute significant insights for further analysis, are eliminated. ‘ID’ is merely a distinct identifier, while ‘Z_CostContact’ and ‘Z_Revenue’ do not display variability, making them uninformative for a predictive model.</p></li>
<li><p><strong>Handling Missing Values</strong>: The ‘Income’ feature contains missing values, which require attention. Depending on the shape of the distribution, these missing values will be addressed using either its mean or median imputation.</p></li>
<li><p><strong>Derivation of New Features</strong>: New features, ‘Age’, ‘Customer_Tenure’, and ‘Generation’, are engineered from existing ones. ‘Age’ is calculated by subtracting the ‘Year_Birth’ from the current year. ‘Customer_Tenure’ reflects the customer’s length of association with the store and is computed from the ‘Dt_Customer’ feature. The ‘Generation’ is determined based on the ‘Age’ feature and the definitions provided by Pew Research Centre. <code>Total_Purchases</code> and <code>Total_Spending</code> are calculated from <code>NumXPurchase</code> and <code>MntX</code> respectively.</p></li>
<li><p><strong>Encoding of Categorical Variables</strong>: Categorical variables, namely ‘Education’ and ‘Marital_Status’, are encoded into a format suitable for machine learning algorithms. One-hot encoding is a suitable method for this purpose.</p></li>
<li><p><strong>Scaling of Numeric Features</strong>: The features ‘Income’, ‘Recency’, ‘MntX’, and ‘NumXPurchases’ exist in different scales. To ensure that no single feature dominates the model. Scaling methods will be implemented later on as pipelines during experimentation since some machine learning models such as XGBoost and Catboost don’t require feature scaling. This will be tested during the experimentation later on.</p></li>
<li><p><strong>Detection and Treatment of Outliers</strong>: Outliers in features such as ‘Income’, ‘Recency’, ‘MntX’, and ‘NumXPurchases’ can significantly bias the model. Therefore, outlier detection and subsequent treatment, through methods like Z-score or the Interquartile Range (IQR) method, are employed.</p></li>
</ol>
<p><strong>footnotes</strong>: &gt; The ‘Generation’ feature is classified as per the definitions given by the Pew Research Centre: &gt; &gt; - The Silent Generation: Born 1928-1945 (76-93 years old) &gt; - Baby Boomers: Born 1946-1964 (57-75 years old) &gt; - Generation X: Born 1965-1980 (41-56 years old) &gt; - Millennials: Born 1981-1996 (25-40 years old) &gt; - Generation Z: Born 1997-2012 (9-24 years old) &gt; - Generation Alpha: Born 2010-2025 (0-11 years old)</p>
<section id="unnecesary-features-removal-missing-value-handling-and-new-features-generation" class="level4">
<h4 class="anchored" data-anchor-id="unnecesary-features-removal-missing-value-handling-and-new-features-generation">3.2.1 Unnecesary Features Removal, Missing Value Handling, and New Features Generation</h4>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df_raw.copy(deep<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Redundant Features Removal</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop([<span class="st">'ID'</span>, <span class="st">'Z_CostContact'</span>, <span class="st">'Z_Revenue'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Missing Values Handling</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Income'</span>] <span class="op">=</span> df[<span class="st">'Income'</span>].fillna(df[<span class="st">'Income'</span>].median())</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. New Features Derivation</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Age from Year_Birth</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>current_year <span class="op">=</span> datetime.now().year</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Age'</span>] <span class="op">=</span> current_year <span class="op">-</span> df[<span class="st">'Year_Birth'</span>]</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(<span class="st">'Year_Birth'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Total Purchase</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Total_Purchases'</span>] <span class="op">=</span> df[<span class="st">'NumDealsPurchases'</span>] <span class="op">+</span> df[<span class="st">'NumWebPurchases'</span>] <span class="op">+</span> df[<span class="st">'NumCatalogPurchases'</span>] <span class="op">+</span> df[<span class="st">'NumStorePurchases'</span>]</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Customer_Tenure</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Dt_Customer'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'Dt_Customer'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'</span><span class="sc">%d</span><span class="st">-%m-%Y'</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>last_recorded_date <span class="op">=</span> df[<span class="st">'Dt_Customer'</span>].<span class="bu">max</span>()</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Customer_Tenure'</span>] <span class="op">=</span> (last_recorded_date <span class="op">-</span> df[<span class="st">'Dt_Customer'</span>]).dt.days</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Total Spending</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>product_columns <span class="op">=</span> [<span class="st">'MntWines'</span>, <span class="st">'MntFruits'</span>, <span class="st">'MntMeatProducts'</span>, <span class="st">'MntFishProducts'</span>, <span class="st">'MntSweetProducts'</span>, <span class="st">'MntGoldProds'</span>]</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Total_Spending'</span>] <span class="op">=</span> df[product_columns].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Living_With feature based on Kidhome and Teenhome</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Kidhome'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'Teenhome'</span>] <span class="op">==</span> <span class="dv">0</span>),</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Kidhome'</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'Teenhome'</span>] <span class="op">==</span> <span class="dv">1</span>),</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Kidhome'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df[<span class="st">'Teenhome'</span>] <span class="op">==</span> <span class="dv">1</span>),</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>choices <span class="op">=</span> [<span class="st">'With_Kids'</span>, <span class="st">'With_Teens'</span>, <span class="st">'With_Kids_and_Teens'</span>]</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Living_With'</span>] <span class="op">=</span> np.select(conditions, choices, default<span class="op">=</span><span class="st">'Alone'</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Is_Parent feature</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Is_Parent'</span>] <span class="op">=</span> (df[<span class="st">'Kidhome'</span>] <span class="op">+</span> df[<span class="st">'Teenhome'</span>]).<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="dv">1</span> <span class="cf">if</span> x <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="dv">0</span>)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Define generations</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">76</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">93</span>),</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">57</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">75</span>),</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">41</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">56</span>),</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">25</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">40</span>),</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">9</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">24</span>),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Age'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'Age'</span>] <span class="op">&lt;=</span> <span class="dv">11</span>),</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>choices <span class="op">=</span> [<span class="st">'Silent_Generation'</span>, <span class="st">'Baby_Boomers'</span>, <span class="st">'Generation_X'</span>, <span class="st">'Millennials'</span>, <span class="st">'Generation_Z'</span>, <span class="st">'Generation_Alpha'</span>]</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Generation'</span>] <span class="op">=</span> np.select(conditions, choices, default<span class="op">=</span><span class="st">'Unknown'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="outlier-detection" class="level3">
<h3 class="anchored" data-anchor-id="outlier-detection">3.2.2. Outlier Detection</h3>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>num_df <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>np.number)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>nunique_df <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>num_df.<span class="bu">apply</span>(pd.Series.nunique), columns<span class="op">=</span>[<span class="st">'nunique'</span>]).rename_axis(<span class="st">'variables'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>selection <span class="op">=</span> nunique_df[nunique_df[<span class="st">'nunique'</span>] <span class="op">&gt;</span> <span class="dv">5</span>].index</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#plotly frame setup</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>to_plot <span class="op">=</span> num_df[selection]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># number of variables to plot</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>num_vars <span class="op">=</span> <span class="bu">len</span>(to_plot.columns)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate number of rows and columns for the subplot grid</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>plot_nrows <span class="op">=</span> <span class="bu">int</span>(np.ceil(num_vars <span class="op">/</span> <span class="dv">4</span>))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># create subplot titles</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>subplot_titles <span class="op">=</span> <span class="bu">list</span>(to_plot.columns) <span class="op">+</span> [<span class="st">''</span>] <span class="op">*</span> (plot_nrows <span class="op">*</span> <span class="dv">4</span> <span class="op">-</span> num_vars) </span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># create subplots</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> make_subplots(rows<span class="op">=</span>plot_nrows, cols<span class="op">=</span><span class="dv">4</span>, subplot_titles<span class="op">=</span><span class="bu">tuple</span>(subplot_titles))</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co"># add traces</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col_name <span class="kw">in</span> <span class="bu">enumerate</span>(to_plot.columns):</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> i <span class="op">//</span> <span class="dv">4</span> <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    col <span class="op">=</span> i <span class="op">%</span> <span class="dv">4</span> <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    fig.add_trace(go.Box(y<span class="op">=</span>to_plot[col_name], name<span class="op">=</span>col_name), row<span class="op">=</span>row, col<span class="op">=</span>col)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>fig.update_layout(height<span class="op">=</span><span class="dv">1400</span>, width<span class="op">=</span><span class="dv">1200</span>, showlegend<span class="op">=</span><span class="va">False</span>, template<span class="op">=</span><span class="st">'plotly_dark'</span>, title<span class="op">=</span><span class="st">'Boxplot of Numerical Features'</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>fig.update_xaxes(visible<span class="op">=</span><span class="va">False</span>, showticklabels<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>Unable to display output for mime type(s): application/vnd.plotly.v1+json</code></pre>
</div>
</div>
<p><img src="figures/boxplots.png" width="90%"></p>
<p><strong>Highlights</strong></p>
<p>The boxplot above shows that tere are possible outliers on the following features: - Income, MntFruits, MntMeatProducts, MntSweetProducts, MntGoldProds, MntFishProducts, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumWebVisitsMonth, Age, and TotalSpent</p>
<p>Before deciding wether outliers found should be remove, let’s calculate how many percentage of the data are considered as outliers by the Inter-quartile Range method used by the boxplot</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#count outliers</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Q1 <span class="op">=</span> num_df.quantile(<span class="fl">0.25</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>Q3 <span class="op">=</span> num_df.quantile(<span class="fl">0.75</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> Q3<span class="op">-</span>Q1</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#outlier dataframe</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>outlier_count <span class="op">=</span> ((num_df <span class="op">&lt;</span> (Q1<span class="op">-</span><span class="fl">1.5</span><span class="op">*</span>IQR)) <span class="op">|</span> (num_df <span class="op">&gt;</span> (Q3 <span class="op">+</span> <span class="fl">1.5</span><span class="op">*</span>IQR))).<span class="bu">sum</span>() <span class="co">#outlier count </span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>outlier_df <span class="op">=</span> pd.DataFrame(outlier_count, columns<span class="op">=</span>[<span class="st">'outlier_count'</span>]).rename_axis(<span class="st">'variable'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>outlier_df[<span class="st">'percentage'</span>] <span class="op">=</span> outlier_df[<span class="st">'outlier_count'</span>]<span class="op">/</span><span class="bu">len</span>(num_df)<span class="op">*</span><span class="dv">100</span> <span class="co">#outlier percentage columns</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.precision'</span>, <span class="dv">2</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>outlier_df.sort_values(<span class="st">'outlier_count'</span>, ascending<span class="op">=</span><span class="va">False</span>).style.background_gradient(cmap<span class="op">=</span><span class="st">'gist_heat'</span>).set_caption(<span class="st">'Outlier Count'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">

<style type="text/css">
#T_c4159_row0_col0, #T_c4159_row0_col1 {
  background-color: #ffffff;
  color: #000000;
}
#T_c4159_row1_col0, #T_c4159_row1_col1 {
  background-color: #ff7d00;
  color: #f1f1f1;
}
#T_c4159_row2_col0, #T_c4159_row2_col1 {
  background-color: #ff5b00;
  color: #f1f1f1;
}
#T_c4159_row3_col0, #T_c4159_row3_col1 {
  background-color: #ff5500;
  color: #f1f1f1;
}
#T_c4159_row4_col0, #T_c4159_row4_col1 {
  background-color: #ed3d00;
  color: #f1f1f1;
}
#T_c4159_row5_col0, #T_c4159_row5_col1 {
  background-color: #c90d00;
  color: #f1f1f1;
}
#T_c4159_row6_col0, #T_c4159_row6_col1 {
  background-color: #c00100;
  color: #f1f1f1;
}
#T_c4159_row7_col0, #T_c4159_row7_col1, #T_c4159_row8_col0, #T_c4159_row8_col1 {
  background-color: #ba0000;
  color: #f1f1f1;
}
#T_c4159_row9_col0, #T_c4159_row9_col1 {
  background-color: #a50000;
  color: #f1f1f1;
}
#T_c4159_row10_col0, #T_c4159_row10_col1 {
  background-color: #620000;
  color: #f1f1f1;
}
#T_c4159_row11_col0, #T_c4159_row11_col1 {
  background-color: #270000;
  color: #f1f1f1;
}
#T_c4159_row12_col0, #T_c4159_row12_col1 {
  background-color: #210000;
  color: #f1f1f1;
}
#T_c4159_row13_col0, #T_c4159_row13_col1 {
  background-color: #1a0000;
  color: #f1f1f1;
}
#T_c4159_row14_col0, #T_c4159_row14_col1 {
  background-color: #180000;
  color: #f1f1f1;
}
#T_c4159_row15_col0, #T_c4159_row15_col1, #T_c4159_row16_col0, #T_c4159_row16_col1 {
  background-color: #090000;
  color: #f1f1f1;
}
#T_c4159_row17_col0, #T_c4159_row17_col1 {
  background-color: #040000;
  color: #f1f1f1;
}
#T_c4159_row18_col0, #T_c4159_row18_col1, #T_c4159_row19_col0, #T_c4159_row19_col1 {
  background-color: #030000;
  color: #f1f1f1;
}
#T_c4159_row20_col0, #T_c4159_row20_col1 {
  background-color: #020000;
  color: #f1f1f1;
}
#T_c4159_row21_col0, #T_c4159_row21_col1, #T_c4159_row22_col0, #T_c4159_row22_col1, #T_c4159_row23_col0, #T_c4159_row23_col1, #T_c4159_row24_col0, #T_c4159_row24_col1, #T_c4159_row25_col0, #T_c4159_row25_col1, #T_c4159_row26_col0, #T_c4159_row26_col1 {
  background-color: #000000;
  color: #f1f1f1;
}
</style>
<table id="T_c4159">
  <caption>Outlier Count</caption>
  <thead>
    <tr>
      <th class="blank level0">&nbsp;</th>
      <th id="T_c4159_level0_col0" class="col_heading level0 col0">outlier_count</th>
      <th id="T_c4159_level0_col1" class="col_heading level0 col1">percentage</th>
    </tr>
    <tr>
      <th class="index_name level0">variable</th>
      <th class="blank col0">&nbsp;</th>
      <th class="blank col1">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_c4159_level0_row0" class="row_heading level0 row0">Response</th>
      <td id="T_c4159_row0_col0" class="data row0 col0">334</td>
      <td id="T_c4159_row0_col1" class="data row0 col1">14.910714</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row1" class="row_heading level0 row1">MntSweetProducts</th>
      <td id="T_c4159_row1_col0" class="data row1 col0">248</td>
      <td id="T_c4159_row1_col1" class="data row1 col1">11.071429</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row2" class="row_heading level0 row2">MntFruits</th>
      <td id="T_c4159_row2_col0" class="data row2 col0">227</td>
      <td id="T_c4159_row2_col1" class="data row2 col1">10.133929</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row3" class="row_heading level0 row3">MntFishProducts</th>
      <td id="T_c4159_row3_col0" class="data row3 col0">223</td>
      <td id="T_c4159_row3_col1" class="data row3 col1">9.955357</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row4" class="row_heading level0 row4">MntGoldProds</th>
      <td id="T_c4159_row4_col0" class="data row4 col0">207</td>
      <td id="T_c4159_row4_col1" class="data row4 col1">9.241071</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row5" class="row_heading level0 row5">MntMeatProducts</th>
      <td id="T_c4159_row5_col0" class="data row5 col0">175</td>
      <td id="T_c4159_row5_col1" class="data row5 col1">7.812500</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row6" class="row_heading level0 row6">AcceptedCmp4</th>
      <td id="T_c4159_row6_col0" class="data row6 col0">167</td>
      <td id="T_c4159_row6_col1" class="data row6 col1">7.455357</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row7" class="row_heading level0 row7">AcceptedCmp3</th>
      <td id="T_c4159_row7_col0" class="data row7 col0">163</td>
      <td id="T_c4159_row7_col1" class="data row7 col1">7.276786</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row8" class="row_heading level0 row8">AcceptedCmp5</th>
      <td id="T_c4159_row8_col0" class="data row8 col0">163</td>
      <td id="T_c4159_row8_col1" class="data row8 col1">7.276786</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row9" class="row_heading level0 row9">AcceptedCmp1</th>
      <td id="T_c4159_row9_col0" class="data row9 col0">144</td>
      <td id="T_c4159_row9_col1" class="data row9 col1">6.428571</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row10" class="row_heading level0 row10">NumDealsPurchases</th>
      <td id="T_c4159_row10_col0" class="data row10 col0">86</td>
      <td id="T_c4159_row10_col1" class="data row10 col1">3.839286</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row11" class="row_heading level0 row11">MntWines</th>
      <td id="T_c4159_row11_col0" class="data row11 col0">35</td>
      <td id="T_c4159_row11_col1" class="data row11 col1">1.562500</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row12" class="row_heading level0 row12">AcceptedCmp2</th>
      <td id="T_c4159_row12_col0" class="data row12 col0">30</td>
      <td id="T_c4159_row12_col1" class="data row12 col1">1.339286</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row13" class="row_heading level0 row13">NumCatalogPurchases</th>
      <td id="T_c4159_row13_col0" class="data row13 col0">23</td>
      <td id="T_c4159_row13_col1" class="data row13 col1">1.026786</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row14" class="row_heading level0 row14">Complain</th>
      <td id="T_c4159_row14_col0" class="data row14 col0">21</td>
      <td id="T_c4159_row14_col1" class="data row14 col1">0.937500</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row15" class="row_heading level0 row15">Income</th>
      <td id="T_c4159_row15_col0" class="data row15 col0">8</td>
      <td id="T_c4159_row15_col1" class="data row15 col1">0.357143</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row16" class="row_heading level0 row16">NumWebVisitsMonth</th>
      <td id="T_c4159_row16_col0" class="data row16 col0">8</td>
      <td id="T_c4159_row16_col1" class="data row16 col1">0.357143</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row17" class="row_heading level0 row17">NumWebPurchases</th>
      <td id="T_c4159_row17_col0" class="data row17 col0">4</td>
      <td id="T_c4159_row17_col1" class="data row17 col1">0.178571</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row18" class="row_heading level0 row18">Age</th>
      <td id="T_c4159_row18_col0" class="data row18 col0">3</td>
      <td id="T_c4159_row18_col1" class="data row18 col1">0.133929</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row19" class="row_heading level0 row19">Total_Spending</th>
      <td id="T_c4159_row19_col0" class="data row19 col0">3</td>
      <td id="T_c4159_row19_col1" class="data row19 col1">0.133929</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row20" class="row_heading level0 row20">Total_Purchases</th>
      <td id="T_c4159_row20_col0" class="data row20 col0">2</td>
      <td id="T_c4159_row20_col1" class="data row20 col1">0.089286</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row21" class="row_heading level0 row21">Customer_Tenure</th>
      <td id="T_c4159_row21_col0" class="data row21 col0">0</td>
      <td id="T_c4159_row21_col1" class="data row21 col1">0.000000</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row22" class="row_heading level0 row22">NumStorePurchases</th>
      <td id="T_c4159_row22_col0" class="data row22 col0">0</td>
      <td id="T_c4159_row22_col1" class="data row22 col1">0.000000</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row23" class="row_heading level0 row23">Kidhome</th>
      <td id="T_c4159_row23_col0" class="data row23 col0">0</td>
      <td id="T_c4159_row23_col1" class="data row23 col1">0.000000</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row24" class="row_heading level0 row24">Recency</th>
      <td id="T_c4159_row24_col0" class="data row24 col0">0</td>
      <td id="T_c4159_row24_col1" class="data row24 col1">0.000000</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row25" class="row_heading level0 row25">Teenhome</th>
      <td id="T_c4159_row25_col0" class="data row25 col0">0</td>
      <td id="T_c4159_row25_col1" class="data row25 col1">0.000000</td>
    </tr>
    <tr>
      <th id="T_c4159_level0_row26" class="row_heading level0 row26">Is_Parent</th>
      <td id="T_c4159_row26_col0" class="data row26 col0">0</td>
      <td id="T_c4159_row26_col1" class="data row26 col1">0.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<p>The table above presents the number of data points identified as outliers via the Interquartile Range (IQR) method for each variable. Additionally, the percentage of outliers in relation to the overall observations is displayed in the second column.</p>
<p>A significant percentage of data labeled as outliers is noticed in several variables. Such outliers may not indeed be outliers but could be representative of the inherent variability within the population parameter for each respective variable. Therefore, caution is advised before deciding to remove these outliers.</p>
<p>Therefore, instead of a blanket removal, a more selective approach will be adopted. Outliers will be defined as those data points where the distance from the nearest data point is significantly large. An example of this can be seen in the ‘MntMeatProducts’ variable, where values ranging from 1582 to 1725 are significantly distant from the next lower value of 984. This approach will be uniformly applied to all variables.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filter multiple conditions</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> conjunction(<span class="op">*</span>conditions):</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> functools.<span class="bu">reduce</span>(np.logical_and, conditions)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>cond1 <span class="op">=</span> df.Age <span class="op">&lt;</span> <span class="dv">90</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>cond2 <span class="op">=</span> df.Income <span class="op">&lt;</span> <span class="dv">150000</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>cond3 <span class="op">=</span> df.NumCatalogPurchases <span class="op">&lt;</span> <span class="dv">11</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>cond4 <span class="op">=</span> df.NumWebVisitsMonth <span class="op">&lt;</span> <span class="dv">13</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>cond5 <span class="op">=</span> df.NumWebPurchases <span class="op">&lt;</span> <span class="dv">20</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>cond6 <span class="op">=</span> df.MntSweetProducts <span class="op">&lt;</span> <span class="dv">200</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>cond7 <span class="op">=</span> df.MntMeatProducts <span class="op">&lt;</span> <span class="dv">1500</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>cond8 <span class="op">=</span> df.MntGoldProds <span class="op">&lt;</span> <span class="dv">290</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[conjunction(cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8)]</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of data points before outlier removal:"</span>, <span class="bu">len</span>(df_raw))</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of data points after outlier removal:"</span>, <span class="bu">len</span>(df))</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percentage of data points removed: </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>((<span class="bu">len</span>(df_raw) <span class="op">-</span> <span class="bu">len</span>(df)) <span class="op">/</span> <span class="bu">len</span>(df_raw) <span class="op">*</span> <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of data points before outlier removal: 2240
Number of data points after outlier removal: 2195
Percentage of data points removed: 2.01%</code></pre>
</div>
</div>
<p>Several conditional filters were applied on the features Age, Income, NumCatalogPurchases, NumWebVisitsMonth, NumWebPurchases, MntSweetProducts, MntMeatProducts, and MntGoldProds to detect and remove outliers. Each condition was defined to exclude values beyond a certain threshold, which was determined based on the data exploration and boxplot visualization.</p>
<p>Upon applying all the conditions simultaneously on the data, the outliers were effectively removed. The number of observations after this process is 2195, which means 45 data points were identified as outliers and excluded from the dataset.</p>
<p>In terms of percentage, approximately 2.01% of the original data was removed during this outlier treatment process. The removal of these outliers should improve the overall quality of the data and potentially enhance the performance of any subsequent model training and predictions.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">4. Exploratory Data Analysis</h2>
<section id="identifying-influential-factors-in-customer-responses" class="level3">
<h3 class="anchored" data-anchor-id="identifying-influential-factors-in-customer-responses">4.1 Identifying Influential Factors in Customer Responses</h3>
<p>For optimizing marketing strategies, understanding the factor that can influence customer’s likelihood of accepting offers is paramount. The relationships between customer attributes and their responses to the last campaign have been explored.</p>
<p>It’s crucial to emphasize the importance of relative values in our analysis, as they allow for effective comparisons that can pinpoint which factors warrant the most effective comparison for optimizing marketing strategy.</p>
<p>The findings are as follows:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of numerical columns</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>numerical_cols <span class="op">=</span> [<span class="st">'Income'</span>, <span class="st">'Kidhome'</span>, <span class="st">'Teenhome'</span>, <span class="st">'Recency'</span>, <span class="st">'MntWines'</span>, <span class="st">'MntFruits'</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'MntMeatProducts'</span>, <span class="st">'MntFishProducts'</span>, <span class="st">'MntSweetProducts'</span>, <span class="st">'MntGoldProds'</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'NumDealsPurchases'</span>, <span class="st">'NumWebPurchases'</span>, <span class="st">'NumCatalogPurchases'</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'NumStorePurchases'</span>, <span class="st">'NumWebVisitsMonth'</span>, <span class="st">'Age'</span>, <span class="st">'Total_Purchases'</span>, </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Customer_Tenure'</span>, <span class="st">'Total_Spending'</span>]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty dictionary to hold column names, their correlation with 'Response' and p-value</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>correlation_dict <span class="op">=</span> {}</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the numerical columns and compute Point Biserial Correlation</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> numerical_cols:</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    correlation, p_value <span class="op">=</span> pointbiserialr(df[<span class="st">'Response'</span>], df[col])</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    correlation_dict[col] <span class="op">=</span> {<span class="st">'Correlation'</span>: correlation, <span class="st">'P_value'</span>: p_value}</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the dictionary to a DataFrame</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>correlation_df <span class="op">=</span> pd.DataFrame(correlation_dict).T.reset_index().rename(columns<span class="op">=</span>{<span class="st">'index'</span>:<span class="st">'Variable'</span>})</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>correlation_df.sort_values(<span class="st">'Correlation'</span>, ascending<span class="op">=</span><span class="va">False</span>).style.<span class="op">\</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    background_gradient(subset<span class="op">=</span>[<span class="st">'Correlation'</span>], cmap<span class="op">=</span><span class="st">'gist_heat'</span>).<span class="op">\</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>        set_caption(<span class="st">'Point-Biserial Correlation'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">

<style type="text/css">
#T_86d94_row0_col1 {
  background-color: #ffffff;
  color: #000000;
}
#T_86d94_row1_col1 {
  background-color: #fff1e3;
  color: #000000;
}
#T_86d94_row2_col1 {
  background-color: #ffe9d3;
  color: #000000;
}
#T_86d94_row3_col1 {
  background-color: #ffe1c3;
  color: #000000;
}
#T_86d94_row4_col1 {
  background-color: #ffbd7b;
  color: #000000;
}
#T_86d94_row5_col1 {
  background-color: #ff9933;
  color: #000000;
}
#T_86d94_row6_col1 {
  background-color: #ff9123;
  color: #000000;
}
#T_86d94_row7_col1 {
  background-color: #ff8913;
  color: #f1f1f1;
}
#T_86d94_row8_col1 {
  background-color: #ff8307;
  color: #f1f1f1;
}
#T_86d94_row9_col1, #T_86d94_row10_col1 {
  background-color: #ff5f00;
  color: #f1f1f1;
}
#T_86d94_row11_col1 {
  background-color: #ff5700;
  color: #f1f1f1;
}
#T_86d94_row12_col1 {
  background-color: #c20300;
  color: #f1f1f1;
}
#T_86d94_row13_col1 {
  background-color: #b00000;
  color: #f1f1f1;
}
#T_86d94_row14_col1 {
  background-color: #ae0000;
  color: #f1f1f1;
}
#T_86d94_row15_col1 {
  background-color: #990000;
  color: #f1f1f1;
}
#T_86d94_row16_col1 {
  background-color: #680000;
  color: #f1f1f1;
}
#T_86d94_row17_col1 {
  background-color: #270000;
  color: #f1f1f1;
}
#T_86d94_row18_col1 {
  background-color: #000000;
  color: #f1f1f1;
}
</style>
<table id="T_86d94">
  <caption>Point-Biserial Correlation</caption>
  <thead>
    <tr>
      <th class="blank level0">&nbsp;</th>
      <th id="T_86d94_level0_col0" class="col_heading level0 col0">Variable</th>
      <th id="T_86d94_level0_col1" class="col_heading level0 col1">Correlation</th>
      <th id="T_86d94_level0_col2" class="col_heading level0 col2">P_value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_86d94_level0_row0" class="row_heading level0 row0">18</th>
      <td id="T_86d94_row0_col0" class="data row0 col0">Total_Spending</td>
      <td id="T_86d94_row0_col1" class="data row0 col1">0.256426</td>
      <td id="T_86d94_row0_col2" class="data row0 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row1" class="row_heading level0 row1">6</th>
      <td id="T_86d94_row1_col0" class="data row1 col0">MntMeatProducts</td>
      <td id="T_86d94_row1_col1" class="data row1 col1">0.243658</td>
      <td id="T_86d94_row1_col2" class="data row1 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row2" class="row_heading level0 row2">4</th>
      <td id="T_86d94_row2_col0" class="data row2 col0">MntWines</td>
      <td id="T_86d94_row2_col1" class="data row2 col1">0.235974</td>
      <td id="T_86d94_row2_col2" class="data row2 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row3" class="row_heading level0 row3">12</th>
      <td id="T_86d94_row3_col0" class="data row3 col0">NumCatalogPurchases</td>
      <td id="T_86d94_row3_col1" class="data row3 col1">0.228098</td>
      <td id="T_86d94_row3_col2" class="data row3 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row4" class="row_heading level0 row4">17</th>
      <td id="T_86d94_row4_col0" class="data row4 col0">Customer_Tenure</td>
      <td id="T_86d94_row4_col1" class="data row4 col1">0.196252</td>
      <td id="T_86d94_row4_col2" class="data row4 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row5" class="row_heading level0 row5">0</th>
      <td id="T_86d94_row5_col0" class="data row5 col0">Income</td>
      <td id="T_86d94_row5_col1" class="data row5 col1">0.163569</td>
      <td id="T_86d94_row5_col2" class="data row5 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row6" class="row_heading level0 row6">11</th>
      <td id="T_86d94_row6_col0" class="data row6 col0">NumWebPurchases</td>
      <td id="T_86d94_row6_col1" class="data row6 col1">0.156850</td>
      <td id="T_86d94_row6_col2" class="data row6 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row7" class="row_heading level0 row7">16</th>
      <td id="T_86d94_row7_col0" class="data row7 col0">Total_Purchases</td>
      <td id="T_86d94_row7_col1" class="data row7 col1">0.150160</td>
      <td id="T_86d94_row7_col2" class="data row7 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row8" class="row_heading level0 row8">9</th>
      <td id="T_86d94_row8_col0" class="data row8 col0">MntGoldProds</td>
      <td id="T_86d94_row8_col1" class="data row8 col1">0.145443</td>
      <td id="T_86d94_row8_col2" class="data row8 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row9" class="row_heading level0 row9">8</th>
      <td id="T_86d94_row9_col0" class="data row9 col0">MntSweetProducts</td>
      <td id="T_86d94_row9_col1" class="data row9 col1">0.113166</td>
      <td id="T_86d94_row9_col2" class="data row9 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row10" class="row_heading level0 row10">5</th>
      <td id="T_86d94_row10_col0" class="data row10 col0">MntFruits</td>
      <td id="T_86d94_row10_col1" class="data row10 col1">0.112847</td>
      <td id="T_86d94_row10_col2" class="data row10 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row11" class="row_heading level0 row11">7</th>
      <td id="T_86d94_row11_col0" class="data row11 col0">MntFishProducts</td>
      <td id="T_86d94_row11_col1" class="data row11 col1">0.106046</td>
      <td id="T_86d94_row11_col2" class="data row11 col2">0.000001</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row12" class="row_heading level0 row12">13</th>
      <td id="T_86d94_row12_col0" class="data row12 col0">NumStorePurchases</td>
      <td id="T_86d94_row12_col1" class="data row12 col1">0.031110</td>
      <td id="T_86d94_row12_col2" class="data row12 col2">0.145098</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row13" class="row_heading level0 row13">10</th>
      <td id="T_86d94_row13_col0" class="data row13 col0">NumDealsPurchases</td>
      <td id="T_86d94_row13_col1" class="data row13 col1">0.009872</td>
      <td id="T_86d94_row13_col2" class="data row13 col2">0.643886</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row14" class="row_heading level0 row14">14</th>
      <td id="T_86d94_row14_col0" class="data row14 col0">NumWebVisitsMonth</td>
      <td id="T_86d94_row14_col1" class="data row14 col1">0.007695</td>
      <td id="T_86d94_row14_col2" class="data row14 col2">0.718610</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row15" class="row_heading level0 row15">15</th>
      <td id="T_86d94_row15_col0" class="data row15 col0">Age</td>
      <td id="T_86d94_row15_col1" class="data row15 col1">-0.018682</td>
      <td id="T_86d94_row15_col2" class="data row15 col2">0.381668</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row16" class="row_heading level0 row16">1</th>
      <td id="T_86d94_row16_col0" class="data row16 col0">Kidhome</td>
      <td id="T_86d94_row16_col1" class="data row16 col1">-0.076050</td>
      <td id="T_86d94_row16_col2" class="data row16 col2">0.000362</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row17" class="row_heading level0 row17">2</th>
      <td id="T_86d94_row17_col0" class="data row17 col0">Teenhome</td>
      <td id="T_86d94_row17_col1" class="data row17 col1">-0.152760</td>
      <td id="T_86d94_row17_col2" class="data row17 col2">0.000000</td>
    </tr>
    <tr>
      <th id="T_86d94_level0_row18" class="row_heading level0 row18">3</th>
      <td id="T_86d94_row18_col0" class="data row18 col0">Recency</td>
      <td id="T_86d94_row18_col1" class="data row18 col1">-0.200908</td>
      <td id="T_86d94_row18_col2" class="data row18 col2">0.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<p>The figures can be interpreted as such:</p>
<p><strong>Possitively correlated with Response</strong> - The strongest positive correlation has been found with Total_Spending (p-value &lt; 0.05). This statistically significant finding suggests that a higher likelihood of accepting the latest offers is associated with customers who have spent more. - A similar positive trend is seen with MntMeatProducts and MntWines (both p-values &lt; 0.05), indicating a higher tendency to respond positively to campaigns among customers with higher expenditures on meat products and wines than those who spend high on other product categories.</p>
<p><strong>Negatively correlated with Response (Inverse Relationship)</strong></p>
<ul>
<li>Conversely, <code>Recency</code>, or the recency of a customer’s last purchase, shows a negative correlation (p-value &lt; 0.05). This suggests that the more recent a purchase made by a customer, the less likely they are to accept new offers. This could be interpreted as recent buyers still being satisfied with their purchases and possibly not being in the market for more, even when a new offer is presented.</li>
</ul>
<p><strong>No significant correlation with Response</strong> - Interestingly, no significant influence on the decision to accept the latest offers is detected from the number of purchases a customer made with a discount (NumDealsPurchases). This may suggest that discounts are not the primary motivator for these customers or that some improvements need to be made on discount offering strategy.This finding is also statistically significant.</p>
<p>To assess the relationship between the categorical variables in the dataset and the customer’s response to the latest campaign (Response), both a Chi-square test of independence and Cramér’s V were conducted.</p>
<ul>
<li><p>The Chi-square statistic and its associated p-value evaluate the statistical significance of the observed relationship, with the p-value providing the probability of obtaining the observed data if no relationship actually exists in the population.</p></li>
<li><p>Cramér’s V provides a measure of the strength of association between two categorical variables, taking values from 0 (indicating no association) to 1 (indicating perfect association).</p></li>
</ul>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cramers_v(x, y):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Calculate Cramér's V statistic for categorial-categorial association."""</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    confusion_matrix <span class="op">=</span> pd.crosstab(x, y)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    chi2 <span class="op">=</span> chi2_contingency(confusion_matrix)[<span class="dv">0</span>]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> confusion_matrix.<span class="bu">sum</span>().<span class="bu">sum</span>()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    phi2 <span class="op">=</span> chi2<span class="op">/</span>n</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    r, k <span class="op">=</span> confusion_matrix.shape</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    phi2corr <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, phi2 <span class="op">-</span> ((k<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(r<span class="op">-</span><span class="dv">1</span>))<span class="op">/</span>(n<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    rcorr <span class="op">=</span> r <span class="op">-</span> ((r<span class="op">-</span><span class="dv">1</span>)<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(n<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    kcorr <span class="op">=</span> k <span class="op">-</span> ((k<span class="op">-</span><span class="dv">1</span>)<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(n<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.sqrt(phi2corr <span class="op">/</span> <span class="bu">min</span>((kcorr<span class="op">-</span><span class="dv">1</span>), (rcorr<span class="op">-</span><span class="dv">1</span>)))</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> chi2_and_cramers_v(df, target, variables):</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> []</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> var <span class="kw">in</span> variables:</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        contingency_table <span class="op">=</span> pd.crosstab(df[target], df[var])</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>        chi2, p, _, _ <span class="op">=</span> stats.chi2_contingency(contingency_table)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> cramers_v(df[var], df[target])</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>        results.append([var, chi2, p, v])</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    results_df <span class="op">=</span> pd.DataFrame(results, columns<span class="op">=</span>[<span class="st">'Variable'</span>, <span class="st">'Chi-square statistic'</span>, <span class="st">'P-value'</span>, <span class="st">'Cramers_V'</span>])</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    results_df <span class="op">=</span> results_df.sort_values(by<span class="op">=</span><span class="st">'Cramers_V'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> results_df</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">'Education'</span>, <span class="st">'Marital_Status'</span>, <span class="st">'Generation'</span>, <span class="st">'AcceptedCmp1'</span>, <span class="st">'AcceptedCmp2'</span>, </span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'AcceptedCmp3'</span>, <span class="st">'AcceptedCmp4'</span>, <span class="st">'AcceptedCmp5'</span>, <span class="st">'Complain'</span>, <span class="st">'Living_With'</span>, <span class="st">'Is_Parent'</span>]</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> chi2_and_cramers_v(df, target<span class="op">=</span><span class="st">'Response'</span>, variables<span class="op">=</span>categorical_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>results_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Chi-square statistic</th>
      <th>P-value</th>
      <th>Cramers_V</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>AcceptedCmp5</td>
      <td>213.03</td>
      <td>3.00e-48</td>
      <td>0.31</td>
    </tr>
    <tr>
      <th>3</th>
      <td>AcceptedCmp1</td>
      <td>170.52</td>
      <td>5.71e-39</td>
      <td>0.28</td>
    </tr>
    <tr>
      <th>5</th>
      <td>AcceptedCmp3</td>
      <td>135.74</td>
      <td>2.27e-31</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Is_Parent</td>
      <td>87.72</td>
      <td>7.53e-21</td>
      <td>0.20</td>
    </tr>
    <tr>
      <th>6</th>
      <td>AcceptedCmp4</td>
      <td>70.43</td>
      <td>4.77e-17</td>
      <td>0.18</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Living_With</td>
      <td>71.29</td>
      <td>2.26e-15</td>
      <td>0.18</td>
    </tr>
    <tr>
      <th>4</th>
      <td>AcceptedCmp2</td>
      <td>60.75</td>
      <td>6.48e-15</td>
      <td>0.17</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Marital_Status</td>
      <td>56.38</td>
      <td>7.95e-10</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>0</th>
      <td>Education</td>
      <td>25.12</td>
      <td>4.76e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Generation</td>
      <td>8.95</td>
      <td>3.00e-02</td>
      <td>0.05</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Complain</td>
      <td>0.00</td>
      <td>1.00e+00</td>
      <td>0.00</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>The results of the combined analysis using the Chi-square test of independence and Cramér’s V statistic are as follows:</p>
<ul>
<li><p><strong>AcceptedCmp5, AcceptedCmp1, and AcceptedCmp3:</strong> These variables related to the acceptance of offers in previous campaigns showed the strongest associations with the latest campaign response. Their high Chi-square values and almost zero p-values indicated statistically significant relationships, while their Cramér’s V values (0.31, 0.28, and 0.25 respectively) suggested a moderate strength of association. This implies that previous acceptances of campaign offers have a significant influence on the likelihood of accepting future campaigns. Thus, focusing on such customers could greatly enhance the success rates of future campaigns.</p></li>
<li><p><strong>Is_Parent:</strong> With a Cramér’s V value of 0.20, this variable displayed a significant yet weaker association with the campaign response. This suggests that being a parent might influence the decision to accept the offer, indicating that campaigns specifically designed for parents could yield higher response rates.</p></li>
<li><p><strong>AcceptedCmp4, Living_With, and AcceptedCmp2:</strong> Although these variables had weaker associations with the campaign response (Cramér’s V = 0.18, 0.18, and 0.17 respectively), they were statistically significant, indicating their potential influence on the outcome. Therefore, these variables should not be disregarded in campaign design.</p></li>
<li><p><strong>Marital_Status and Education:</strong> These variables exhibited weaker associations with the campaign response (Cramér’s V = 0.15 and 0.10 respectively). However, their statistical significance suggests that they might subtly influence customer behavior. Thus, campaign designs that consider different marital statuses and education levels might lead to modest improvements in response rates.</p></li>
<li><p><strong>Generation:</strong> Despite its weak association with campaign responses (Cramér’s V = 0.05), the ‘Generation’ variable is statistically significant, indicating that generational categories could subtly impact response rates. This also underlines the importance of appropriate data categorization - while the ‘Age’ variable as a standalone factor didn’t demonstrate statistical significance, segmenting it into ‘Generation’ has revealed potential behavioral insights.</p></li>
<li><p><strong>Complain:</strong> There was no significant association between this variable and the campaign response (Cramér’s V = 0.00). This suggests that a customer’s complaint history does not appear to significantly impact their decision to accept the offer in the latest campaign. As a result, it may not be necessary to prioritize this variable in the context of campaign design.</p></li>
</ul>
</section>
<section id="enhancing-statistical-significance-variable-grouping-analysis" class="level3">
<h3 class="anchored" data-anchor-id="enhancing-statistical-significance-variable-grouping-analysis">4.2 Enhancing Statistical Significance: Variable Grouping Analysis</h3>
<p>The successful grouping of the ‘Age’ variable, which contributed to significant statistical results, serves as the inspiration to apply similar treatment to other numerical variables. Particularly, the variables that did not previously demonstrate statistical significance, such as ‘NumStorePurchases’, ‘NumDealsPurchases’, and ‘NumWebVisitsMonth’, will be targeted. Furthermore, other numerical variables with sufficient unique values will also be grouped.</p>
<p>Discretization by quartiles has been selected as the chosen grouping technique due to its robustness in handling outliers and skewness, its ability to transform numerical data into categorical while preserving the distribution properties, and the interpretability it offers by dividing the data into quartiles representing different levels of the variable.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dicretize_stats_test(df, variable_name, target_name, min_quartiles<span class="op">=</span><span class="dv">2</span>, max_quartiles<span class="op">=</span><span class="dv">21</span>):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Perform a chi-square test and calculate Cramér's V for a variable discretized into different numbers of quartiles."""</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Initialize an empty list to store the results</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    test_results <span class="op">=</span> []</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Loop through different numbers of quartiles</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> quartiles <span class="kw">in</span> <span class="bu">range</span>(min_quartiles, max_quartiles): </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Discretize the variable into quartiles</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        variable_quartiles <span class="op">=</span> pd.qcut(df[variable_name], quartiles, labels<span class="op">=</span><span class="va">False</span>, duplicates<span class="op">=</span><span class="st">'drop'</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Create a contingency table</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>        contingency_table <span class="op">=</span> pd.crosstab(df[target_name], variable_quartiles)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Perform the chi-square test</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>        chi2, p, _, _ <span class="op">=</span> chi2_contingency(contingency_table)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Compute Cramer's V</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> cramers_v(df[target_name], variable_quartiles)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Append the results to the list</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>        test_results.append([<span class="ss">f'</span><span class="sc">{</span>variable_name<span class="sc">}</span><span class="ss">_</span><span class="sc">{</span>quartiles<span class="sc">}</span><span class="ss">'</span>, chi2, p, v])</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert the list to a DataFrame</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    test_results_df <span class="op">=</span> pd.DataFrame(test_results, columns<span class="op">=</span>[<span class="st">'Variable'</span>, <span class="st">'Chi-square statistic'</span>, <span class="st">'P-value'</span>, <span class="st">'Cramers_V'</span>])</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sort the DataFrame by the chi-square statistic in descending order</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    test_results_df <span class="op">=</span> test_results_df.sort_values(<span class="st">'Chi-square statistic'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> test_results_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dicretize_stats_test(df, <span class="st">'NumStorePurchases'</span>, <span class="st">'Response'</span>, min_quartiles<span class="op">=</span><span class="dv">2</span>, max_quartiles<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Chi-square statistic</th>
      <th>P-value</th>
      <th>Cramers_V</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>NumStorePurchases_9</td>
      <td>27.46</td>
      <td>1.19e-04</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>4</th>
      <td>NumStorePurchases_6</td>
      <td>26.28</td>
      <td>7.87e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NumStorePurchases_5</td>
      <td>24.83</td>
      <td>5.45e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>6</th>
      <td>NumStorePurchases_8</td>
      <td>24.74</td>
      <td>3.82e-04</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>5</th>
      <td>NumStorePurchases_7</td>
      <td>23.95</td>
      <td>2.22e-04</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NumStorePurchases_3</td>
      <td>21.66</td>
      <td>1.98e-05</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NumStorePurchases_4</td>
      <td>18.14</td>
      <td>4.12e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>0</th>
      <td>NumStorePurchases_2</td>
      <td>10.08</td>
      <td>1.50e-03</td>
      <td>0.06</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>The <code>NumStorePurchases</code> variable is best segmented into 6 categories (discretize by 6 quartiles). Here’s why:</p>
<ul>
<li>The statistical significance (p-value: 7.87e-05) is high, showing a meaningful relationship with campaign responses.</li>
<li>The association strength (Cramér’s V: 0.10) is similar across different segmentations.</li>
<li>A 6-category split balances useful insights with easy comprehension for decision-makers.</li>
</ul>
<p>This can guide strategies by highlighting how in-store purchases can affect campaign responses.</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dicretize_stats_test(df, <span class="st">'NumWebVisitsMonth'</span>, <span class="st">'Response'</span>, min_quartiles<span class="op">=</span><span class="dv">2</span>, max_quartiles<span class="op">=</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Chi-square statistic</th>
      <th>P-value</th>
      <th>Cramers_V</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>5</th>
      <td>NumWebVisitsMonth_7</td>
      <td>45.49</td>
      <td>3.74e-08</td>
      <td>0.13</td>
    </tr>
    <tr>
      <th>6</th>
      <td>NumWebVisitsMonth_8</td>
      <td>45.49</td>
      <td>3.74e-08</td>
      <td>0.13</td>
    </tr>
    <tr>
      <th>4</th>
      <td>NumWebVisitsMonth_6</td>
      <td>42.01</td>
      <td>5.86e-08</td>
      <td>0.13</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NumWebVisitsMonth_5</td>
      <td>26.50</td>
      <td>2.51e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NumWebVisitsMonth_4</td>
      <td>19.46</td>
      <td>2.19e-04</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NumWebVisitsMonth_3</td>
      <td>19.39</td>
      <td>6.15e-05</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>0</th>
      <td>NumWebVisitsMonth_2</td>
      <td>1.27</td>
      <td>2.59e-01</td>
      <td>0.01</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>For <code>NumWebVisitsMonth</code>, segmenting into 7 categories proves to be an effective choice. Here’s the rationale:</p>
<ul>
<li>High statistical significance (p-value: 3.74e-08) indicates a robust relationship with campaign responses.</li>
<li>The strength of association (Cramér’s V: 0.13) is consistently strong across different segmentations.</li>
<li>A 7-category split balances comprehensive insights with ease of understanding for non-technical stakeholders.</li>
</ul>
<p>This provides valuable insight into how the frequency of website visits in a month influences campaign responses, informing future online engagement strategies.</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dicretize_stats_test(df, <span class="st">'NumDealsPurchases'</span>, <span class="st">'Response'</span>, min_quartiles<span class="op">=</span><span class="dv">2</span>, max_quartiles<span class="op">=</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Chi-square statistic</th>
      <th>P-value</th>
      <th>Cramers_V</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>5</th>
      <td>NumDealsPurchases_7</td>
      <td>19.15</td>
      <td>7.33e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>6</th>
      <td>NumDealsPurchases_8</td>
      <td>19.15</td>
      <td>7.33e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>4</th>
      <td>NumDealsPurchases_6</td>
      <td>19.03</td>
      <td>2.70e-04</td>
      <td>0.09</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NumDealsPurchases_4</td>
      <td>16.89</td>
      <td>7.46e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NumDealsPurchases_5</td>
      <td>16.89</td>
      <td>7.46e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NumDealsPurchases_3</td>
      <td>14.56</td>
      <td>6.90e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>0</th>
      <td>NumDealsPurchases_2</td>
      <td>0.09</td>
      <td>7.64e-01</td>
      <td>0.00</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>In the case of <code>NumDealsPurchases</code>, our analysis suggests a relatively weak relationship with campaign responses:</p>
<ul>
<li>Across all levels of segmentation, the association (Cramér’s V) stays consistently around 0.08, indicating a weak link with the campaign’s outcome.</li>
<li>The p-values are significant, suggesting a statistically noteworthy relationship. However, their values are larger than those of previously discussed variables, hinting at a weaker effect.</li>
<li>Segmenting <code>NumDealsPurchases</code> into 6 categories seems to be the optimal choice, as it strikes a balance between insights and interpretability while preserving a reasonable level of statistical significance (p-value: 2.70e-04).</li>
</ul>
<p>Although the relationship is weak, it should not be disregarded. The frequency of deal purchases may offer a minor yet valuable hint on customer behavior and preferences that can guide the design of future campaigns.</p>
<p>Then, the same experiment was applied on other variables to decide which quartile value is optimum to use for grouping the values. These includes variables that already shown statistical significance relationship with Response. The reason is that these newly group values might be useful for later modeling stage</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Recency_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'Recency'</span>], q<span class="op">=</span><span class="dv">5</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Total_Spending_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'Total_Spending'</span>], q<span class="op">=</span><span class="dv">6</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'MntMeatProducts_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'MntMeatProducts'</span>], q<span class="op">=</span><span class="dv">5</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'MntWines_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'MntWines'</span>], q<span class="op">=</span><span class="dv">5</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Customer_Tenure_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'Customer_Tenure'</span>], q<span class="op">=</span><span class="dv">6</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Income_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'Income'</span>], q<span class="op">=</span><span class="dv">8</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'NumStorePurchases_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'NumStorePurchases'</span>], q<span class="op">=</span><span class="dv">6</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'NumDealsPurchases_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'NumDealsPurchases'</span>], q<span class="op">=</span><span class="dv">4</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'NumWebVisitsMonth_Grp'</span>] <span class="op">=</span> pd.qcut(df[<span class="st">'NumWebVisitsMonth'</span>], q<span class="op">=</span><span class="dv">7</span>, labels<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">'Education'</span>, <span class="st">'Marital_Status'</span>, <span class="st">'Generation'</span>, <span class="st">'AcceptedCmp1'</span>, <span class="st">'AcceptedCmp2'</span>, </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'AcceptedCmp3'</span>, <span class="st">'AcceptedCmp4'</span>, <span class="st">'AcceptedCmp5'</span>, <span class="st">'Complain'</span>, <span class="st">'Living_With'</span>, <span class="st">'Is_Parent'</span>, </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Recency_Grp'</span>, <span class="st">'Total_Spending_Grp'</span>, <span class="st">'NumStorePurchases_Grp'</span>, <span class="st">'NumDealsPurchases_Grp'</span>, <span class="st">'NumWebVisitsMonth_Grp'</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Income_Grp'</span>, <span class="st">'Customer_Tenure_Grp'</span>, <span class="st">'MntMeatProducts_Grp'</span>, <span class="st">'MntWines_Grp'</span>]</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty list to hold column names, their test statistic, p-value and degrees of freedom</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>chi2_results <span class="op">=</span> []</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the categorical columns and perform Chi-Square test</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> categorical_cols:</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    contingency_table <span class="op">=</span> pd.crosstab(df[<span class="st">'Response'</span>], df[col])</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    chi2, p, _, _ <span class="op">=</span> stats.chi2_contingency(contingency_table)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    chi2_results.append([col, chi2, p])</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a><span class="co"># # Convert the list to a DataFrame</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="co"># chi2_df = pd.DataFrame(chi2_results, columns=['Variable', 'Chi-square statistic', 'P-value'])</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="co"># chi2_df.sort_values('Chi-square statistic', ascending=False)</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>chi2_and_cramers_v(df, target<span class="op">=</span><span class="st">'Response'</span>, variables<span class="op">=</span>categorical_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Chi-square statistic</th>
      <th>P-value</th>
      <th>Cramers_V</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>AcceptedCmp5</td>
      <td>213.03</td>
      <td>3.00e-48</td>
      <td>0.31</td>
    </tr>
    <tr>
      <th>3</th>
      <td>AcceptedCmp1</td>
      <td>170.52</td>
      <td>5.71e-39</td>
      <td>0.28</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Total_Spending_Grp</td>
      <td>153.91</td>
      <td>1.97e-31</td>
      <td>0.26</td>
    </tr>
    <tr>
      <th>5</th>
      <td>AcceptedCmp3</td>
      <td>135.74</td>
      <td>2.27e-31</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Income_Grp</td>
      <td>129.12</td>
      <td>9.58e-25</td>
      <td>0.24</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Recency_Grp</td>
      <td>107.35</td>
      <td>2.67e-22</td>
      <td>0.22</td>
    </tr>
    <tr>
      <th>18</th>
      <td>MntMeatProducts_Grp</td>
      <td>102.62</td>
      <td>2.72e-21</td>
      <td>0.21</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Customer_Tenure_Grp</td>
      <td>100.86</td>
      <td>3.48e-20</td>
      <td>0.21</td>
    </tr>
    <tr>
      <th>19</th>
      <td>MntWines_Grp</td>
      <td>92.15</td>
      <td>4.61e-19</td>
      <td>0.20</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Is_Parent</td>
      <td>87.72</td>
      <td>7.53e-21</td>
      <td>0.20</td>
    </tr>
    <tr>
      <th>6</th>
      <td>AcceptedCmp4</td>
      <td>70.43</td>
      <td>4.77e-17</td>
      <td>0.18</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Living_With</td>
      <td>71.29</td>
      <td>2.26e-15</td>
      <td>0.18</td>
    </tr>
    <tr>
      <th>4</th>
      <td>AcceptedCmp2</td>
      <td>60.75</td>
      <td>6.48e-15</td>
      <td>0.17</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Marital_Status</td>
      <td>56.38</td>
      <td>7.95e-10</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>15</th>
      <td>NumWebVisitsMonth_Grp</td>
      <td>45.49</td>
      <td>3.74e-08</td>
      <td>0.13</td>
    </tr>
    <tr>
      <th>13</th>
      <td>NumStorePurchases_Grp</td>
      <td>26.28</td>
      <td>7.87e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>0</th>
      <td>Education</td>
      <td>25.12</td>
      <td>4.76e-05</td>
      <td>0.10</td>
    </tr>
    <tr>
      <th>14</th>
      <td>NumDealsPurchases_Grp</td>
      <td>16.89</td>
      <td>7.46e-04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Generation</td>
      <td>8.95</td>
      <td>3.00e-02</td>
      <td>0.05</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Complain</td>
      <td>0.00</td>
      <td>1.00e+00</td>
      <td>0.00</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="84">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#save to csv</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># df.to_csv('marketing_campaign_clean.csv', index=False)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analyzing-significant-variables-for-deep-insights" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-significant-variables-for-deep-insights">4.3 Analyzing Significant Variables for Deep Insights</h3>
<div class="cell" data-tags="[&quot;hide_code&quot;]" data-execution_count="21">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.cm <span class="im">as</span> cm</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> ticker <span class="im">as</span> plticker</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> ticker</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib <span class="im">as</span> mpl</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> discretize(v, v_intervals, use_quartiles<span class="op">=</span><span class="va">False</span>, use_continuous_bins<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(v, (pd.core.series.Series, np.ndarray)) <span class="kw">and</span> <span class="bu">isinstance</span>(v_intervals, (<span class="bu">list</span>, np.ndarray)) <span class="kw">and</span> <span class="bu">len</span>(np.unique(v)) <span class="op">!=</span> <span class="bu">len</span>(v_intervals):</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"length of interval must match unique items in array"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(v, (<span class="bu">str</span>)) <span class="kw">and</span> <span class="bu">isinstance</span>(v_intervals, (<span class="bu">list</span>, np.ndarray)):</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>        <span class="co">#name of variable instead of array and list of intervals used</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">isinstance</span>(v_intervals, <span class="bu">list</span>): v_intervals <span class="op">=</span> np.array(v_intervals)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> v, v_intervals</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (np.isin(v.dtype, [<span class="bu">int</span>, <span class="bu">float</span>, <span class="st">'int8'</span>, <span class="st">'int16'</span>, <span class="st">'int32'</span>, <span class="st">'float16'</span>, <span class="st">'float32'</span>])) <span class="kw">and</span> (<span class="bu">isinstance</span>(v_intervals, (<span class="bu">int</span>))) <span class="kw">and</span> (<span class="bu">len</span>(np.unique(v)) <span class="op">&gt;=</span> v_intervals) <span class="kw">and</span> (<span class="bu">max</span>(v) <span class="op">&gt;</span> <span class="bu">min</span>(v)):</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>        <span class="co">#v is discretizable, otherwise assumed to be already discretized</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> use_continuous_bins:</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> use_quartiles:</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>                v, bins <span class="op">=</span> pd.qcut(v, v_intervals, duplicates<span class="op">=</span><span class="st">'drop'</span>, retbins<span class="op">=</span><span class="va">True</span>, labels<span class="op">=</span><span class="va">True</span>, precision<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>                v, bins <span class="op">=</span> pd.cut(v, v_intervals, duplicates<span class="op">=</span><span class="st">'drop'</span>, retbins<span class="op">=</span><span class="va">True</span>, labels<span class="op">=</span><span class="va">True</span>, precision<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> use_quartiles:</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>                v <span class="op">=</span> pd.qcut(v, v_intervals, duplicates<span class="op">=</span><span class="st">'drop'</span>, precision<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>                v <span class="op">=</span> pd.cut(v, v_intervals, duplicates<span class="op">=</span><span class="st">'drop'</span>, precision<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.isin(v.dtype, [<span class="bu">object</span>, <span class="st">'category'</span>]):</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> <span class="bu">isinstance</span>(v, (pd.core.series.Series)):</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>            v <span class="op">=</span> pd.Series(v)</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>        bins <span class="op">=</span> np.sort(np.unique(v)).astype(<span class="bu">str</span>)</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> v.astype(<span class="bu">str</span>)</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>        bin_dict <span class="op">=</span> {bins[i]:i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(bins))}</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> v.replace(bin_dict)</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>        bins <span class="op">=</span> np.unique(v)</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(v_intervals, (<span class="bu">list</span>, np.ndarray)) <span class="kw">and</span> <span class="bu">len</span>(bins) <span class="op">==</span> <span class="bu">len</span>(v_intervals):</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>        bins <span class="op">=</span> v_intervals</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> v, bins</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_prob_progression(x, y, x_intervals<span class="op">=</span><span class="dv">7</span>, use_quartiles<span class="op">=</span><span class="va">False</span>,<span class="op">\</span></span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>                          xlabel<span class="op">=</span><span class="va">None</span>, ylabel<span class="op">=</span><span class="va">None</span>, title<span class="op">=</span><span class="va">None</span>, text<span class="op">=</span><span class="va">None</span>, model<span class="op">=</span><span class="va">None</span>, X_df<span class="op">=</span><span class="va">None</span>, x_col<span class="op">=</span><span class="va">None</span>,<span class="op">\</span></span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>                         mean_line<span class="op">=</span><span class="va">False</span>, figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">6</span>), x_margin<span class="op">=</span><span class="fl">0.01</span>, color<span class="op">=</span><span class="st">'Reds'</span>):</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> x.astype(<span class="bu">int</span>)</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> y.astype(<span class="bu">int</span>)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>): x <span class="op">=</span> np.array(x)</span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(y, <span class="bu">list</span>): y <span class="op">=</span> np.array(y)</span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="kw">not</span> <span class="bu">isinstance</span>(x, (<span class="bu">str</span>, pd.core.series.Series, np.ndarray))) <span class="kw">or</span> (<span class="kw">not</span> <span class="bu">isinstance</span>(y, (<span class="bu">str</span>, pd.core.series.Series, np.ndarray))):</span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"x and y must be either lists, pandas series or numpy arrays. x can be string when dataset is provided seperately"</span>)</span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="bu">isinstance</span>(x, (pd.core.series.Series, np.ndarray)) <span class="kw">and</span> (<span class="bu">len</span>(x.shape) <span class="op">!=</span> <span class="dv">1</span>)) <span class="kw">or</span> ((<span class="bu">isinstance</span>(y, (pd.core.series.Series, np.ndarray))) <span class="kw">and</span> (<span class="bu">len</span>(y.shape) <span class="op">!=</span> <span class="dv">1</span>)):</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"x and y must have a single dimension"</span>)</span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">int</span>)) <span class="kw">and</span> (x_intervals <span class="op">&lt;</span> <span class="dv">2</span>)) <span class="kw">or</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">list</span>, np.ndarray)) <span class="kw">and</span> (<span class="bu">len</span>(x_intervals) <span class="op">&lt;</span> <span class="dv">2</span>)):</span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"there must be at least two intervals to plot"</span>)</span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> np.isin(y.dtype, [<span class="bu">int</span>, <span class="bu">float</span>, <span class="st">'int8'</span>, <span class="st">'int16'</span>, <span class="st">'int32'</span>, <span class="st">'float16'</span>, <span class="st">'float32'</span>]):</span>
<span id="cb24-61"><a href="#cb24-61" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"y dimension must be a list, pandas series or numpy array of integers or floats"</span>)</span>
<span id="cb24-62"><a href="#cb24-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">max</span>(y) <span class="op">==</span> <span class="bu">min</span>(y):</span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"y dimension must have at least two values"</span>)</span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">len</span>(np.unique(y)) <span class="op">==</span> <span class="dv">2</span> <span class="kw">and</span> ((<span class="bu">max</span>(y) <span class="op">!=</span> <span class="dv">1</span>) <span class="kw">or</span> (<span class="bu">min</span>(y) <span class="op">!=</span> <span class="dv">0</span>)):</span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"y dimension if has two values must have a max of exactly 1 and min of exactly zero"</span>)</span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">len</span>(np.unique(y)) <span class="op">&gt;</span> <span class="dv">2</span> <span class="kw">and</span> ((<span class="bu">max</span>(y) <span class="op">&lt;=</span> <span class="dv">1</span>) <span class="kw">or</span> (<span class="bu">min</span>(y) <span class="op">&gt;=</span> <span class="dv">0</span>)):</span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"y dimension if has more than two values must have range between between 0-1"</span>)</span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>    x_use_continuous_bins <span class="op">=</span> (model <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">list</span>, np.ndarray)))</span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a>    x, x_bins <span class="op">=</span> discretize(x, x_intervals, use_quartiles, x_use_continuous_bins)</span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a>    x_range <span class="op">=</span> [<span class="op">*</span><span class="bu">range</span>(<span class="bu">len</span>(x_bins))]</span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a>    plot_df <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>:x_range})</span>
<span id="cb24-72"><a href="#cb24-72" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (model <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (X_df <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (x_col <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>):</span>
<span id="cb24-73"><a href="#cb24-73" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> model.predict(X_df).squeeze()</span>
<span id="cb24-74"><a href="#cb24-74" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(np.unique(preds)) <span class="op">&lt;=</span> <span class="dv">2</span>:</span>
<span id="cb24-75"><a href="#cb24-75" aria-hidden="true" tabindex="-1"></a>            preds <span class="op">=</span> model.predict_proba(X_df)[:,<span class="dv">1</span>]</span>
<span id="cb24-76"><a href="#cb24-76" aria-hidden="true" tabindex="-1"></a>        x_, _ <span class="op">=</span> discretize(X_df[x_col], x_intervals, use_quartiles, x_use_continuous_bins)</span>
<span id="cb24-77"><a href="#cb24-77" aria-hidden="true" tabindex="-1"></a>        xy_df <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>:x_, <span class="st">'y'</span>:preds})</span>
<span id="cb24-78"><a href="#cb24-78" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb24-79"><a href="#cb24-79" aria-hidden="true" tabindex="-1"></a>        xy_df <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>:x,<span class="st">'y'</span>:y})</span>
<span id="cb24-80"><a href="#cb24-80" aria-hidden="true" tabindex="-1"></a>    probs_df <span class="op">=</span> xy_df.groupby([<span class="st">'x'</span>]).mean().reset_index()</span>
<span id="cb24-81"><a href="#cb24-81" aria-hidden="true" tabindex="-1"></a>    probs_df <span class="op">=</span> pd.merge(plot_df, probs_df, how<span class="op">=</span><span class="st">'left'</span>, on<span class="op">=</span><span class="st">'x'</span>).fillna(<span class="dv">0</span>)</span>
<span id="cb24-82"><a href="#cb24-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-83"><a href="#cb24-83" aria-hidden="true" tabindex="-1"></a>    x_bin_cnt <span class="op">=</span> <span class="bu">len</span>(x_bins)</span>
<span id="cb24-84"><a href="#cb24-84" aria-hidden="true" tabindex="-1"></a>    l_width <span class="op">=</span> <span class="fl">0.933</span></span>
<span id="cb24-85"><a href="#cb24-85" aria-hidden="true" tabindex="-1"></a>    r_width <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb24-86"><a href="#cb24-86" aria-hidden="true" tabindex="-1"></a>    w, h <span class="op">=</span> figsize</span>
<span id="cb24-87"><a href="#cb24-87" aria-hidden="true" tabindex="-1"></a>    wp <span class="op">=</span> (w<span class="op">-</span>l_width<span class="op">-</span>r_width)<span class="op">/</span><span class="fl">9.27356902357</span></span>
<span id="cb24-88"><a href="#cb24-88" aria-hidden="true" tabindex="-1"></a>    xh_margin <span class="op">=</span> ((wp<span class="op">-</span>(x_margin<span class="op">*</span><span class="dv">2</span>))<span class="op">/</span>(x_bin_cnt<span class="op">*</span><span class="dv">2</span>))<span class="op">+</span>x_margin</span>
<span id="cb24-89"><a href="#cb24-89" aria-hidden="true" tabindex="-1"></a>    fig, (ax0, ax1) <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>figsize,<span class="op">\</span></span>
<span id="cb24-90"><a href="#cb24-90" aria-hidden="true" tabindex="-1"></a>                                   gridspec_kw<span class="op">=</span>{<span class="st">'height_ratios'</span>: [<span class="dv">3</span>, <span class="dv">1</span>]})</span>
<span id="cb24-91"><a href="#cb24-91" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> title <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb24-92"><a href="#cb24-92" aria-hidden="true" tabindex="-1"></a>        fig.suptitle(title, fontsize<span class="op">=</span><span class="dv">21</span>)</span>
<span id="cb24-93"><a href="#cb24-93" aria-hidden="true" tabindex="-1"></a>        ax0.text(<span class="fl">0.61</span>, <span class="fl">0.85</span>, text,</span>
<span id="cb24-94"><a href="#cb24-94" aria-hidden="true" tabindex="-1"></a>                 horizontalalignment<span class="op">=</span><span class="st">'left'</span>, verticalalignment<span class="op">=</span><span class="st">'top'</span>, transform<span class="op">=</span>ax0.transAxes, fontsize<span class="op">=</span><span class="dv">9</span>, fontstyle<span class="op">=</span><span class="st">'italic'</span>)</span>
<span id="cb24-95"><a href="#cb24-95" aria-hidden="true" tabindex="-1"></a>        plt.subplots_adjust(top <span class="op">=</span> <span class="fl">0.92</span>, bottom<span class="op">=</span><span class="fl">0.01</span>, hspace<span class="op">=</span><span class="fl">0.001</span>, wspace<span class="op">=</span><span class="fl">0.001</span>)</span>
<span id="cb24-96"><a href="#cb24-96" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb24-97"><a href="#cb24-97" aria-hidden="true" tabindex="-1"></a>        plt.subplots_adjust(top <span class="op">=</span> <span class="fl">0.99</span>, bottom<span class="op">=</span><span class="fl">0.01</span>, hspace<span class="op">=</span><span class="fl">0.001</span>, wspace<span class="op">=</span><span class="fl">0.001</span>)</span>
<span id="cb24-98"><a href="#cb24-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-99"><a href="#cb24-99" aria-hidden="true" tabindex="-1"></a>    ax0.minorticks_on()</span>
<span id="cb24-100"><a href="#cb24-100" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Disable grid for ax0</span></span>
<span id="cb24-101"><a href="#cb24-101" aria-hidden="true" tabindex="-1"></a>    ax0.grid(<span class="va">False</span>)</span>
<span id="cb24-102"><a href="#cb24-102" aria-hidden="true" tabindex="-1"></a>    cmap <span class="op">=</span> mpl.colormaps[color]</span>
<span id="cb24-103"><a href="#cb24-103" aria-hidden="true" tabindex="-1"></a>    num_segments <span class="op">=</span> <span class="bu">len</span>(probs_df[<span class="st">'y'</span>]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb24-104"><a href="#cb24-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-105"><a href="#cb24-105" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(num_segments):</span>
<span id="cb24-106"><a href="#cb24-106" aria-hidden="true" tabindex="-1"></a>        segment <span class="op">=</span> probs_df.iloc[i:i<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb24-107"><a href="#cb24-107" aria-hidden="true" tabindex="-1"></a>        color <span class="op">=</span> cmap(i <span class="op">/</span> num_segments)</span>
<span id="cb24-108"><a href="#cb24-108" aria-hidden="true" tabindex="-1"></a>        sns.lineplot(data<span class="op">=</span>segment, x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span>color, ax<span class="op">=</span>ax0)</span>
<span id="cb24-109"><a href="#cb24-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-110"><a href="#cb24-110" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sns.lineplot(data=probs_df, x='x', y='y', marker='o', ax=ax0)</span></span>
<span id="cb24-111"><a href="#cb24-111" aria-hidden="true" tabindex="-1"></a>    ax0.set_ylabel(<span class="st">'Probability'</span>, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb24-112"><a href="#cb24-112" aria-hidden="true" tabindex="-1"></a>    ax0.set_xlabel(<span class="st">''</span>)</span>
<span id="cb24-113"><a href="#cb24-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-114"><a href="#cb24-114" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> mean_line:</span>
<span id="cb24-115"><a href="#cb24-115" aria-hidden="true" tabindex="-1"></a>        ax0.axhline(y<span class="op">=</span>xy_df.y.mean(), c<span class="op">=</span><span class="st">'#E9EAE5'</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, linestyle<span class="op">=</span><span class="st">'dotted'</span>, label<span class="op">=</span><span class="st">"mean"</span>)</span>
<span id="cb24-116"><a href="#cb24-116" aria-hidden="true" tabindex="-1"></a>        ax0.legend()</span>
<span id="cb24-117"><a href="#cb24-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-118"><a href="#cb24-118" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-119"><a href="#cb24-119" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [cmap(i) <span class="cf">for</span> i <span class="kw">in</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(x_bins))]</span>
<span id="cb24-120"><a href="#cb24-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-121"><a href="#cb24-121" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Disable grid for ax1</span></span>
<span id="cb24-122"><a href="#cb24-122" aria-hidden="true" tabindex="-1"></a>    ax1.grid(<span class="va">False</span>)</span>
<span id="cb24-123"><a href="#cb24-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-124"><a href="#cb24-124" aria-hidden="true" tabindex="-1"></a>    hist <span class="op">=</span> sns.histplot(xy_df, x<span class="op">=</span><span class="st">"x"</span>, stat<span class="op">=</span><span class="st">'probability'</span>, bins<span class="op">=</span>np.arange(x_bin_cnt<span class="op">+</span><span class="dv">1</span>)<span class="op">-</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax1)</span>
<span id="cb24-125"><a href="#cb24-125" aria-hidden="true" tabindex="-1"></a>    <span class="co"># color the bars using the color map</span></span>
<span id="cb24-126"><a href="#cb24-126" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> patch, color <span class="kw">in</span> <span class="bu">zip</span>(hist.patches, colors):</span>
<span id="cb24-127"><a href="#cb24-127" aria-hidden="true" tabindex="-1"></a>        patch.set_facecolor(color) <span class="co"># color depends on the index of the bar</span></span>
<span id="cb24-128"><a href="#cb24-128" aria-hidden="true" tabindex="-1"></a>    ax1.set_ylabel(<span class="st">'Observations'</span>, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb24-129"><a href="#cb24-129" aria-hidden="true" tabindex="-1"></a>    ax1.set_xlabel(xlabel, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb24-130"><a href="#cb24-130" aria-hidden="true" tabindex="-1"></a>    ax1.xaxis.set_major_locator(plticker.MultipleLocator(base<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb24-131"><a href="#cb24-131" aria-hidden="true" tabindex="-1"></a>    ax1.set_xticklabels([<span class="st">''</span>]<span class="op">+</span>[<span class="st">'('</span> <span class="op">+</span> <span class="bu">str</span>(<span class="bu">round</span>(<span class="bu">float</span>(i.split(<span class="st">','</span>)[<span class="dv">0</span>][<span class="dv">1</span>:]))) <span class="op">+</span> <span class="st">', '</span> <span class="op">+</span> <span class="bu">str</span>(<span class="bu">round</span>(<span class="bu">float</span>(i.split(<span class="st">','</span>)[<span class="dv">1</span>][:<span class="op">-</span><span class="dv">1</span>]))) <span class="op">+</span> <span class="st">']'</span> <span class="cf">for</span> i <span class="kw">in</span> x_bins])</span>
<span id="cb24-132"><a href="#cb24-132" aria-hidden="true" tabindex="-1"></a>    ax1.margins(x<span class="op">=</span>x_margin)</span>
<span id="cb24-133"><a href="#cb24-133" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb24-134"><a href="#cb24-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-135"><a href="#cb24-135" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'ggplot'</span>)</span>
<span id="cb24-136"><a href="#cb24-136" aria-hidden="true" tabindex="-1"></a>sns.set_style({<span class="st">'axes.grid'</span> : <span class="va">False</span>})</span>
<span id="cb24-137"><a href="#cb24-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-138"><a href="#cb24-138" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb24-139"><a href="#cb24-139" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.facecolor'</span>: <span class="st">'#00010D'</span>,</span>
<span id="cb24-140"><a href="#cb24-140" aria-hidden="true" tabindex="-1"></a>    <span class="st">'figure.facecolor'</span>: <span class="st">'#00010D'</span>,</span>
<span id="cb24-141"><a href="#cb24-141" aria-hidden="true" tabindex="-1"></a>    <span class="st">'text.color'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-142"><a href="#cb24-142" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.labelcolor'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-143"><a href="#cb24-143" aria-hidden="true" tabindex="-1"></a>    <span class="st">'xtick.color'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-144"><a href="#cb24-144" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ytick.color'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-145"><a href="#cb24-145" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.edgecolor'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-146"><a href="#cb24-146" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.linewidth'</span>: <span class="fl">1.2</span>,</span>
<span id="cb24-147"><a href="#cb24-147" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.titlecolor'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-148"><a href="#cb24-148" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.titlesize'</span>: <span class="dv">14</span>,</span>
<span id="cb24-149"><a href="#cb24-149" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.labelsize'</span>: <span class="dv">12</span>,</span>
<span id="cb24-150"><a href="#cb24-150" aria-hidden="true" tabindex="-1"></a>    <span class="st">'xtick.labelsize'</span>: <span class="dv">10</span>,</span>
<span id="cb24-151"><a href="#cb24-151" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ytick.labelsize'</span>: <span class="dv">10</span>,</span>
<span id="cb24-152"><a href="#cb24-152" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.edgecolor'</span>: <span class="st">'white'</span>,</span>
<span id="cb24-153"><a href="#cb24-153" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.frameon'</span>: <span class="va">False</span>,</span>
<span id="cb24-154"><a href="#cb24-154" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.fontsize'</span>: <span class="dv">10</span>,</span>
<span id="cb24-155"><a href="#cb24-155" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.handlelength'</span>: <span class="fl">1.2</span>,</span>
<span id="cb24-156"><a href="#cb24-156" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.handleheight'</span>: <span class="fl">0.5</span></span>
<span id="cb24-157"><a href="#cb24-157" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="spending-habits" class="level4">
<h4 class="anchored" data-anchor-id="spending-habits">4.3.1 Spending Habits</h4>
<p>Through a detailed examination of customers’ total spending and their expenditures on specific product categories, we can discern important patterns that may guide future marketing strategies. The accompanying plot visually represents these trends, with each spending group’s response rate plotted on the vertical axis against various spending brackets on the horizontal axis.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot_prob_progression is a function that plots the probability of positive responses (e.g., campaign success) across different categories or ranges of a variable. </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#This function will help to visualize how the probability of campaign success changes with the variable of interest.</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plot_prob_progression(df[<span class="st">'Total_Spending'</span>],</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                      df[<span class="st">'Response'</span>],</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                      x_intervals<span class="op">=</span><span class="dv">6</span>, use_quartiles<span class="op">=</span><span class="va">True</span>,  mean_line<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                      title<span class="op">=</span><span class="st">'Probability of Response by Total_Spending'</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                      color<span class="op">=</span><span class="st">'Reds_r'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Below, we delve into these findings:</p>
<ul>
<li><p><strong>Total Spending:</strong> Higher total spending corresponds to a higher response rate to marketing campaigns. Notably, customers spending above the average ($1253-$2525) show a robust response rate of 35%. This group could be targeted with exclusive promotions or loyalty programs to reinforce their engagement. For lower spenders (below $1253), we should experiment with our campaign strategies to better cater to their needs and interests.</p></li>
<li><p><strong>Meat Products:</strong> A similar trend is noticed in meat product spending. Customers spending over $288.6 on meat products respond at a rate of 28%. We could strengthen our meat product-oriented campaigns to appeal to this high-spending segment. For those spending less, consider diversifying our meat product offerings or creating budget-friendly meat bundles to potentially stimulate spending.</p></li>
<li><p><strong>Wines:</strong> Customers spending over $641.33 on wines exhibit the highest response rate at 33% across all categories. This group could benefit from campaigns that highlight our premium wine selections or exclusive wine club memberships. For lower wine spenders, introducing more affordable wines or special deals on bulk purchases might enhance their engagement with our campaigns.</p></li>
</ul>
<p>These findings highlight the importance of adapting our marketing strategies to reflect the different spending levels and preferences of our customer segments. In the next section, we will analyze our customers’ purchasing habits across various channels.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plot_prob_progression(df[<span class="st">'MntMeatProducts'</span>],</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                      df[<span class="st">'Response'</span>],</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                      x_intervals<span class="op">=</span><span class="dv">5</span>, use_quartiles<span class="op">=</span><span class="va">True</span>,  mean_line<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                      title<span class="op">=</span><span class="st">'Probability of Response by MntMeatProducts'</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                      color<span class="op">=</span><span class="st">'Blues_r'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-25-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plot_prob_progression(df[<span class="st">'MntWines'</span>],</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                      df[<span class="st">'Response'</span>],</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                      x_intervals<span class="op">=</span><span class="dv">5</span>, use_quartiles<span class="op">=</span><span class="va">True</span>,  mean_line<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                      title<span class="op">=</span><span class="st">'Probability of Response by MntWines'</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                      color<span class="op">=</span><span class="st">'Purples_r'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="influence-of-purchase-recency-on-campaign-responsiveness" class="level4">
<h4 class="anchored" data-anchor-id="influence-of-purchase-recency-on-campaign-responsiveness">4.3.2 Influence of Purchase Recency on Campaign Responsiveness</h4>
<p>In this section, we turn our focus towards the ‘Recency’ of customers’ last purchase and how this variable, in conjunction with spending habits, influences campaign responsiveness. The plot and data reveal interesting insights into how the time elapsed since the last purchase and expenditure levels shape a customer’s likelihood of responding to marketing campaigns.</p>
<p>Contour plot will be used throughout this section to help us understand the interaction among three variables.</p>
<hr>
<p><strong>Understanding Contour Plot</strong>: &gt; The contour plot makes use of colors to help us understand the response rate’s variation across different levels of Recency and Spending. In these plots, we’ll employ the ‘viridis’ color map, a perceptually uniform representation of data, which moves from purple to yellow. &gt; &gt; The purple region of the plot corresponds to a lower response rate, transitioning to green, and ultimately yellow, which signifies a higher response rate. This progression of color effectively communicates how the response rate to marketing campaigns varies as we traverse from regions representing high recency and low spending (illustrated in purple) towards areas reflecting low recency and high spending (highlighted in yellow). &gt; &gt; As we explore the plots in the subsequent sections, we will observe this color-coded trend consistently across different segments, such as Total Spending, Wines, and Meat Products. These plots will enable us to visually map spending and recency against the response rate to our marketing campaigns.</p>
<hr>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_prob_contour_map(x, y, z, x_intervals<span class="op">=</span><span class="dv">7</span>, y_intervals<span class="op">=</span><span class="dv">7</span>, use_quartiles<span class="op">=</span><span class="va">False</span>, plot_type<span class="op">=</span><span class="st">'contour'</span>,<span class="op">\</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                          xlabel<span class="op">=</span><span class="va">None</span>, ylabel<span class="op">=</span><span class="va">None</span>, title<span class="op">=</span><span class="va">None</span>, model<span class="op">=</span><span class="va">None</span>, X_df<span class="op">=</span><span class="va">None</span>, x_col<span class="op">=</span><span class="va">None</span>, y_col<span class="op">=</span><span class="va">None</span>,<span class="op">\</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                          diff_to_mean<span class="op">=</span><span class="va">False</span>, annotate<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> x.astype(<span class="bu">int</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> y.astype(<span class="bu">int</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> z.astype(<span class="bu">int</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>): x <span class="op">=</span> np.array(x)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(y, <span class="bu">list</span>): y <span class="op">=</span> np.array(y)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(z, <span class="bu">list</span>): z <span class="op">=</span> np.array(z)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="kw">not</span> <span class="bu">isinstance</span>(x, (<span class="bu">str</span>, pd.core.series.Series, np.ndarray))) <span class="kw">or</span> (<span class="kw">not</span> <span class="bu">isinstance</span>(y, (<span class="bu">str</span>, pd.core.series.Series, np.ndarray))) <span class="kw">or</span> (<span class="kw">not</span> <span class="bu">isinstance</span>(z, (pd.core.series.Series, np.ndarray))):</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"x, y and z must be either lists, pandas series or numpy arrays. x and y can be strings when dataset is provided seperately"</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="bu">isinstance</span>(x, (pd.core.series.Series, np.ndarray)) <span class="kw">and</span> (<span class="bu">len</span>(x.shape) <span class="op">!=</span> <span class="dv">1</span>)) <span class="kw">or</span> ((<span class="bu">isinstance</span>(y, (pd.core.series.Series, np.ndarray))) <span class="kw">and</span> (<span class="bu">len</span>(y.shape) <span class="op">!=</span> <span class="dv">1</span>)) <span class="kw">or</span> (<span class="bu">len</span>(z.shape) <span class="op">!=</span> <span class="dv">1</span>):</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"x, y and z must have a single dimension"</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">int</span>)) <span class="kw">and</span> (x_intervals <span class="op">&lt;</span> <span class="dv">2</span>)) <span class="kw">or</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">list</span>, np.ndarray)) <span class="kw">and</span> (<span class="bu">len</span>(x_intervals) <span class="op">&lt;</span> <span class="dv">2</span>)) <span class="kw">or</span> (<span class="bu">isinstance</span>(y_intervals, (<span class="bu">int</span>)) <span class="kw">and</span> (y_intervals <span class="op">&lt;</span> <span class="dv">2</span>)) <span class="kw">or</span> (<span class="bu">isinstance</span>(y_intervals, (<span class="bu">list</span>, np.ndarray)) <span class="kw">and</span> (<span class="bu">len</span>(y_intervals) <span class="op">&lt;</span> <span class="dv">2</span>)):</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"there must be at least two intervals to contour"</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> np.isin(z.dtype, [<span class="bu">int</span>, <span class="bu">float</span>, <span class="st">'int8'</span>, <span class="st">'int16'</span>, <span class="st">'int32'</span>, <span class="st">'float16'</span>, <span class="st">'float32'</span>]):</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"z dimension must be a list, pandas series or numpy array of integers or floats"</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">max</span>(z) <span class="op">==</span> <span class="bu">min</span>(z):</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"z dimension must have at least two values"</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">len</span>(np.unique(z)) <span class="op">==</span> <span class="dv">2</span> <span class="kw">and</span> ((<span class="bu">max</span>(z) <span class="op">!=</span> <span class="dv">1</span>) <span class="kw">or</span> (<span class="bu">min</span>(z) <span class="op">!=</span> <span class="dv">0</span>)):</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"z dimension if has two values must have a max of exactly 1 and min of exactly zero"</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">len</span>(np.unique(z)) <span class="op">&gt;</span> <span class="dv">2</span> <span class="kw">and</span> ((<span class="bu">max</span>(z) <span class="op">&lt;=</span> <span class="dv">1</span>) <span class="kw">or</span> (<span class="bu">min</span>(z) <span class="op">&gt;=</span> <span class="dv">0</span>)):</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">Exception</span>(<span class="st">"z dimension if has more than two values must have range between between 0-1"</span>)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>    x_use_continuous_bins <span class="op">=</span> (model <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (<span class="bu">isinstance</span>(x_intervals, (<span class="bu">list</span>, np.ndarray)))</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    y_use_continuous_bins <span class="op">=</span> (model <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (<span class="bu">isinstance</span>(y_intervals, (<span class="bu">list</span>, np.ndarray)))</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    x, x_bins <span class="op">=</span> discretize(x, x_intervals, use_quartiles, x_use_continuous_bins)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>    y, y_bins <span class="op">=</span> discretize(y, y_intervals, use_quartiles, y_use_continuous_bins)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>    x_range <span class="op">=</span> [<span class="op">*</span><span class="bu">range</span>(<span class="bu">len</span>(x_bins))]</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>    <span class="co">#if isinstance(y_intervals, (int)):</span></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>    y_range <span class="op">=</span> [<span class="op">*</span><span class="bu">range</span>(<span class="bu">len</span>(y_bins))]</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>    <span class="co">#else:</span></span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>    <span class="co">#y_range = y_intervals</span></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>    x_grid, y_grid <span class="op">=</span> np.meshgrid(x_range, y_range)</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>    positions <span class="op">=</span> np.vstack([x_grid.ravel(), y_grid.ravel()])</span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>    plot_df <span class="op">=</span> pd.DataFrame(positions.T, columns<span class="op">=</span>[<span class="st">'x'</span>, <span class="st">'y'</span>])</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (model <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (X_df <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (x_col <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>) <span class="kw">and</span> (y_col <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>):</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> model.predict(X_df).squeeze()</span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(np.unique(preds)) <span class="op">&lt;=</span> <span class="dv">2</span>:</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>            preds <span class="op">=</span> model.predict_proba(X_df)[:,<span class="dv">1</span>]</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>        x_, _ <span class="op">=</span> discretize(X_df[x_col], x_intervals, use_quartiles, x_use_continuous_bins)</span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>        y_, _ <span class="op">=</span> discretize(X_df[y_col], y_intervals, use_quartiles, y_use_continuous_bins)</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>        xyz_df <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>:x_, <span class="st">'y'</span>:y_, <span class="st">'z'</span>:preds})</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>        xyz_df <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>:x,<span class="st">'y'</span>:y,<span class="st">'z'</span>:z})</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>    probs_df <span class="op">=</span> xyz_df.groupby([<span class="st">'x'</span>,<span class="st">'y'</span>]).mean().reset_index()        </span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>    probs_df <span class="op">=</span> pd.merge(plot_df, probs_df, how<span class="op">=</span><span class="st">'left'</span>, on<span class="op">=</span>[<span class="st">'x'</span>,<span class="st">'y'</span>]).fillna(<span class="dv">0</span>)</span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> diff_to_mean:</span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a>        expected_value <span class="op">=</span> xyz_df.z.mean()</span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>        probs_df[<span class="st">'z'</span>] <span class="op">=</span> probs_df[<span class="st">'z'</span>] <span class="op">-</span> expected_value</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>        cmap <span class="op">=</span> plt.cm.RdYlBu</span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>        cmap <span class="op">=</span> plt.cm.viridis</span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a>    grid_probs <span class="op">=</span> np.reshape(probs_df.z.to_numpy(), x_grid.shape)</span>
<span id="cb28-55"><a href="#cb28-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-56"><a href="#cb28-56" aria-hidden="true" tabindex="-1"></a>    x_bin_cnt <span class="op">=</span> <span class="bu">len</span>(x_bins)</span>
<span id="cb28-57"><a href="#cb28-57" aria-hidden="true" tabindex="-1"></a>    y_bin_cnt <span class="op">=</span> <span class="bu">len</span>(y_bins)</span>
<span id="cb28-58"><a href="#cb28-58" aria-hidden="true" tabindex="-1"></a>    fig, (ax_top, ax_bottom) <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">9</span>),<span class="op">\</span></span>
<span id="cb28-59"><a href="#cb28-59" aria-hidden="true" tabindex="-1"></a>                                   gridspec_kw<span class="op">=</span>{<span class="st">'height_ratios'</span>: [<span class="dv">1</span>, <span class="dv">7</span>], <span class="st">'width_ratios'</span>: [<span class="dv">6</span>, <span class="dv">1</span>]})</span>
<span id="cb28-60"><a href="#cb28-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> title <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb28-61"><a href="#cb28-61" aria-hidden="true" tabindex="-1"></a>        fig.suptitle(title, fontsize<span class="op">=</span><span class="dv">21</span>)</span>
<span id="cb28-62"><a href="#cb28-62" aria-hidden="true" tabindex="-1"></a>        plt.subplots_adjust(top <span class="op">=</span> <span class="fl">0.95</span>, bottom<span class="op">=</span><span class="fl">0.01</span>, hspace<span class="op">=</span><span class="fl">0.001</span>, wspace<span class="op">=</span><span class="fl">0.001</span>)</span>
<span id="cb28-63"><a href="#cb28-63" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-64"><a href="#cb28-64" aria-hidden="true" tabindex="-1"></a>        plt.subplots_adjust(top <span class="op">=</span> <span class="fl">0.99</span>, bottom<span class="op">=</span><span class="fl">0.01</span>, hspace<span class="op">=</span><span class="fl">0.001</span>, wspace<span class="op">=</span><span class="fl">0.001</span>)</span>
<span id="cb28-65"><a href="#cb28-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-66"><a href="#cb28-66" aria-hidden="true" tabindex="-1"></a>    sns.set_style(<span class="va">None</span>)</span>
<span id="cb28-67"><a href="#cb28-67" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sns.set_style({'axes.facecolor':'black', 'grid.color': 'white'})</span></span>
<span id="cb28-68"><a href="#cb28-68" aria-hidden="true" tabindex="-1"></a>    sns.histplot(xyz_df, x<span class="op">=</span><span class="st">'x'</span>, stat<span class="op">=</span><span class="st">'probability'</span>, bins<span class="op">=</span>np.arange(x_bin_cnt<span class="op">+</span><span class="dv">1</span>)<span class="op">-</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'dimgray'</span>, ax<span class="op">=</span>ax_top[<span class="dv">0</span>])</span>
<span id="cb28-69"><a href="#cb28-69" aria-hidden="true" tabindex="-1"></a>    ax_top[<span class="dv">0</span>].set_xticks([])</span>
<span id="cb28-70"><a href="#cb28-70" aria-hidden="true" tabindex="-1"></a>    ax_top[<span class="dv">0</span>].set_yticks([])</span>
<span id="cb28-71"><a href="#cb28-71" aria-hidden="true" tabindex="-1"></a>    ax_top[<span class="dv">0</span>].set_xlabel(<span class="st">''</span>)</span>
<span id="cb28-72"><a href="#cb28-72" aria-hidden="true" tabindex="-1"></a>    ax_top[<span class="dv">0</span>].set_ylabel(<span class="st">''</span>)</span>
<span id="cb28-73"><a href="#cb28-73" aria-hidden="true" tabindex="-1"></a>    ax_top[<span class="dv">1</span>].set_visible(<span class="va">False</span>)</span>
<span id="cb28-74"><a href="#cb28-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-75"><a href="#cb28-75" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> plot_type <span class="op">==</span> <span class="st">'contour'</span>:</span>
<span id="cb28-76"><a href="#cb28-76" aria-hidden="true" tabindex="-1"></a>        ax_bottom[<span class="dv">0</span>].contour(</span>
<span id="cb28-77"><a href="#cb28-77" aria-hidden="true" tabindex="-1"></a>            x_grid,</span>
<span id="cb28-78"><a href="#cb28-78" aria-hidden="true" tabindex="-1"></a>            y_grid,</span>
<span id="cb28-79"><a href="#cb28-79" aria-hidden="true" tabindex="-1"></a>            grid_probs,</span>
<span id="cb28-80"><a href="#cb28-80" aria-hidden="true" tabindex="-1"></a>            colors<span class="op">=</span>(<span class="st">'w'</span>,)</span>
<span id="cb28-81"><a href="#cb28-81" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb28-82"><a href="#cb28-82" aria-hidden="true" tabindex="-1"></a>        mappable <span class="op">=</span> ax_bottom[<span class="dv">0</span>].contourf(</span>
<span id="cb28-83"><a href="#cb28-83" aria-hidden="true" tabindex="-1"></a>            x_grid,</span>
<span id="cb28-84"><a href="#cb28-84" aria-hidden="true" tabindex="-1"></a>            y_grid,</span>
<span id="cb28-85"><a href="#cb28-85" aria-hidden="true" tabindex="-1"></a>            grid_probs,</span>
<span id="cb28-86"><a href="#cb28-86" aria-hidden="true" tabindex="-1"></a>            cmap<span class="op">=</span>cmap</span>
<span id="cb28-87"><a href="#cb28-87" aria-hidden="true" tabindex="-1"></a>        ) </span>
<span id="cb28-88"><a href="#cb28-88" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-89"><a href="#cb28-89" aria-hidden="true" tabindex="-1"></a>        mappable <span class="op">=</span> ax_bottom[<span class="dv">0</span>].imshow(grid_probs, cmap<span class="op">=</span>plt.cm.viridis,<span class="op">\</span></span>
<span id="cb28-90"><a href="#cb28-90" aria-hidden="true" tabindex="-1"></a>                                      interpolation<span class="op">=</span><span class="st">'nearest'</span>, aspect<span class="op">=</span><span class="st">'auto'</span>)</span>
<span id="cb28-91"><a href="#cb28-91" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> annotate:</span>
<span id="cb28-92"><a href="#cb28-92" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(y_bin_cnt):</span>
<span id="cb28-93"><a href="#cb28-93" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(x_bin_cnt):</span>
<span id="cb28-94"><a href="#cb28-94" aria-hidden="true" tabindex="-1"></a>                    text <span class="op">=</span> ax_bottom[<span class="dv">0</span>].text(j, i, <span class="st">"</span><span class="sc">{:.1%}</span><span class="st">"</span>.<span class="bu">format</span>(grid_probs[i, j]), fontsize<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb28-95"><a href="#cb28-95" aria-hidden="true" tabindex="-1"></a>                                             ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span><span class="st">"w"</span>)</span>
<span id="cb28-96"><a href="#cb28-96" aria-hidden="true" tabindex="-1"></a>            ax_bottom[<span class="dv">0</span>].grid(<span class="va">False</span>)</span>
<span id="cb28-97"><a href="#cb28-97" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb28-98"><a href="#cb28-98" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">0</span>].xaxis.set_major_locator(plticker.MultipleLocator(base<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb28-99"><a href="#cb28-99" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">0</span>].set_xticklabels([<span class="st">''</span>] <span class="op">+</span> <span class="bu">list</span>(x_bins))</span>
<span id="cb28-100"><a href="#cb28-100" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">0</span>].yaxis.set_major_locator(plticker.MultipleLocator(base<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb28-101"><a href="#cb28-101" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">0</span>].set_yticklabels([<span class="st">''</span>] <span class="op">+</span> <span class="bu">list</span>(y_bins))</span>
<span id="cb28-102"><a href="#cb28-102" aria-hidden="true" tabindex="-1"></a>    <span class="co">#ax_bottom[0].margins(x=0.04, y=0.04)</span></span>
<span id="cb28-103"><a href="#cb28-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-104"><a href="#cb28-104" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> xlabel <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb28-105"><a href="#cb28-105" aria-hidden="true" tabindex="-1"></a>        ax_bottom[<span class="dv">0</span>].set_xlabel(xlabel, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb28-106"><a href="#cb28-106" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb28-107"><a href="#cb28-107" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> ylabel <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb28-108"><a href="#cb28-108" aria-hidden="true" tabindex="-1"></a>        ax_bottom[<span class="dv">0</span>].set_ylabel(ylabel, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb28-109"><a href="#cb28-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-110"><a href="#cb28-110" aria-hidden="true" tabindex="-1"></a>    cbar <span class="op">=</span> plt.colorbar(mappable, ax<span class="op">=</span>ax_bottom[<span class="dv">1</span>])</span>
<span id="cb28-111"><a href="#cb28-111" aria-hidden="true" tabindex="-1"></a>    cbar.ax.set_ylabel(<span class="st">'Probability'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb28-112"><a href="#cb28-112" aria-hidden="true" tabindex="-1"></a>    cbar.ax.tick_params(labelsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb28-113"><a href="#cb28-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-114"><a href="#cb28-114" aria-hidden="true" tabindex="-1"></a>    sns.histplot(xyz_df, x<span class="op">=</span><span class="st">'x'</span>, stat<span class="op">=</span><span class="st">'probability'</span>, bins<span class="op">=</span>np.arange(x_bin_cnt<span class="op">+</span><span class="dv">1</span>)<span class="op">-</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'dimgray'</span>, ax<span class="op">=</span>ax_top[<span class="dv">0</span>])</span>
<span id="cb28-115"><a href="#cb28-115" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">1</span>].set_xticks([])</span>
<span id="cb28-116"><a href="#cb28-116" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">1</span>].set_yticks([])</span>
<span id="cb28-117"><a href="#cb28-117" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">1</span>].set_xlabel(<span class="st">''</span>)</span>
<span id="cb28-118"><a href="#cb28-118" aria-hidden="true" tabindex="-1"></a>    ax_bottom[<span class="dv">1</span>].set_ylabel(<span class="st">''</span>)</span>
<span id="cb28-119"><a href="#cb28-119" aria-hidden="true" tabindex="-1"></a>    sns.set_style(<span class="va">None</span>)</span>
<span id="cb28-120"><a href="#cb28-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-121"><a href="#cb28-121" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>plot_prob_contour_map(df.Total_Spending, df.Recency, df.Response, use_quartiles<span class="op">=</span><span class="va">True</span>, x_intervals<span class="op">=</span><span class="dv">6</span>, y_intervals<span class="op">=</span><span class="dv">5</span>, xlabel<span class="op">=</span><span class="st">'Total_Spending'</span>, ylabel<span class="op">=</span><span class="st">'Recency'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-28-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Insights on Total Spending &amp; Recency:</p>
<ul>
<li>Customers who have made a purchase most recently (0-19 days) and are also high spenders ($1253-$2525) exhibit the highest response rate, at an impressive 56%. This pattern underscores that our recent high-spenders are the most engaged, signaling that more frequent, personalized campaigns could yield considerable benefits with this group.</li>
<li>This trend extends to customers with a slightly longer purchase gap (19-39 days). High-spending customers in this group also demonstrate a significant response rate of 42%, emphasizing the importance of maintaining regular engagement even with customers whose last purchase was up to a month ago.</li>
<li>Conversely, customers who have not made a purchase in a considerable while (79-99 days), irrespective of their spending category, have generally lower response rates, with the highest being only 18% among those spending between $1253-$2525.</li>
</ul>
<p>When we delve into specific product categories, a similar pattern emerges:</p>
<ul>
<li>For both wine and meat products, customers with a recent purchase (0-19 days) and high spending stand out with the highest response rates (53% for wine and 52% for meat products). Additionally, customers with a purchase history extending to 19-39 days also maintain a substantial response rate, with 35% for wine and 32% for meat products.</li>
<li>In stark contrast, customers who have not purchased recently (79-99 days) exhibit lower response rates across all spending levels in both product categories.</li>
</ul>
<p>The data from this analysis underscores that customer engagement tends to wane as the time since their last purchase increases. Therefore, keeping regular interactions with customers, particularly those in the higher spending brackets, is crucial to maintaining their engagement and responsiveness to campaigns.</p>
<p>For customers who have been away for longer, retargeting campaigns, possibly offering special discounts or showcasing new products, could help reignite their interest. Lower spenders in this group might be encouraged to engage more through personalized, value-oriented campaigns that resonate with their shopping habits and preferences.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>plot_prob_contour_map(df.MntWines, df.Recency, df.Response, use_quartiles<span class="op">=</span><span class="va">True</span>, x_intervals<span class="op">=</span><span class="dv">5</span>, y_intervals<span class="op">=</span><span class="dv">7</span>, xlabel<span class="op">=</span><span class="st">'MntWines'</span>, ylabel<span class="op">=</span><span class="st">'Recency'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>In the next section, we will continue to delve into customer behaviors and their impact on campaign responsiveness.</p>
</section>
</section>
<section id="utilizing-insignificant-variables-for-deep-insights" class="level3">
<h3 class="anchored" data-anchor-id="utilizing-insignificant-variables-for-deep-insights">4.4 Utilizing Insignificant Variables for Deep Insights</h3>
<section id="numwebvisitsmonth-analysis" class="level4">
<h4 class="anchored" data-anchor-id="numwebvisitsmonth-analysis">4.4.1 NumWebVisitsMonth Analysis</h4>
<p>NumWebVisitsMonth represents the number of times a customer visits the company’s website within a month. To understand its influence on customer responses, a logistic regression was built. Let’s first look at the model’s reliability before delving into the insights:</p>
<div class="cell" data-execution_count="85">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>R <span class="op">-</span>i df</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>r_df <span class="op">&lt;-</span> df</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">&lt;-</span> glm(Response <span class="op">~</span> Total_Spending <span class="op">*</span> NumWebVisitsMonth, data <span class="op">=</span> r_df, family <span class="op">=</span> binomial)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">|&gt;</span> tidy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 5
  term                              estimate std.error statistic  p.value
  &lt;chr&gt;                                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                      -6.07     0.431        -14.1  4.01e-45
2 Total_Spending                    0.00316  0.000295      10.7  8.30e-27
3 NumWebVisitsMonth                 0.538    0.0606         8.88 6.69e-19
4 Total_Spending:NumWebVisitsMonth -0.000299 0.0000478     -6.25 4.00e-10</code></pre>
</div>
</div>
<div class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>R</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">|&gt;</span> model_performance()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC      |     AICc |      BIC | Tjur's R2 |  RMSE | Sigma | Log_loss | Score_log | Score_spherical |   PCP
-----------------------------------------------------------------------------------------------------------
1621.435 | 1621.453 | 1644.211 |     0.113 | 0.335 | 1.000 |    0.368 |   -55.766 |           0.003 | 0.776</code></pre>
</div>
</div>
<p>With an AIC of 1621.435 and a relatively high PCP of 0.776, the model exhibits a decent fit. While the Tjur’s R2 is at 0.113 indicating a moderate goodness of fit, the other metrics collectively suggest that the findings based on this model can be considered reliable for drawing insights.</p>
<p>Customer Engagement:</p>
<ul>
<li><p>Positive Sign: An increased number of visits implies customers are engaging with the website regularly. This could be due to various reasons – compelling content, interest in products, or even habitual browsing.</p></li>
<li><p>Caveat: It’s essential to differentiate between valuable engagement and potential dissatisfaction. If a user visits frequently but doesn’t respond positively, they might be facing issues with site functionality or content clarity.</p></li>
</ul>
<p>Interaction with Total Spending:</p>
<p>The relationship between the number of web visits and total spending is nuanced. As customers visit more, there’s a diminishing effect of spending on the likelihood of them responding. This can be due to:</p>
<ul>
<li><p>Window Shopping: Browsing without intent to purchase.</p></li>
<li><p>Searching for Deals: Awaiting discounts or product restocks.</p></li>
<li><p>User Experience: The site might be less intuitive for frequent visitors.</p></li>
</ul>
<p><strong>Johnson-Neyman Interval Analysis</strong> :</p>
<p>The plot bewlow showcases the conditional effect of total spending on response, based on the number of web visits. Notably, total spending’s impact becomes especially pronounced when NumWebVisitsMonth is outside the 9.18 to 13.03 range. Given the maximum observed value for web visits in the dataset is 10, this interval is largely hypothetical but offers intriguing possibilities for customer behavior.</p>
<div class="cell" data-execution_count="84">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>R </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>johnson_neyman(model <span class="op">=</span> logit_model , pred <span class="op">=</span> Total_Spending, modx <span class="op">=</span> NumWebVisitsMonth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>JOHNSON-NEYMAN INTERVAL 

When NumWebVisitsMonth is OUTSIDE the interval [9.18, 13.03], the slope of
Total_Spending is p &lt; .05.

Note: The range of observed values of NumWebVisitsMonth is [0.00, 10.00]
</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="marketing_campaign_eda_files/figure-html/cell-32-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Potential Business Strategies Focused on Web Visits: 1. <strong>Website Audit</strong>: Given the importance of web visits, consider a comprehensive website audit. Use tools to track where users spend the most time, and what pages or products they frequently visit.</p>
<ol start="2" type="1">
<li><p><strong>Feedback Mechanisms</strong>: Introduce pop-ups or short surveys asking frequent visitors about their experience. Direct feedback can pinpoint exact issues or needs.</p></li>
<li><p><strong>Optimize for Mobile</strong>: Ensure the website is mobile-optimized. A significant number of users might be accessing through mobile devices. A seamless mobile experience can improve the quality of visits.</p></li>
<li><p><strong>Personalization</strong>: Frequent visitors should have a more personalized experience. Use cookies or account information to tailor content, products, or deals to individual user preferences.</p></li>
<li><p><strong>Loyalty Programs</strong>: Reward frequent visitors with loyalty points or exclusive deals. This not only incentivizes visits but can also increase the conversion rate.</p></li>
<li><p><strong>Re-targeting &amp; Notifications</strong>: If users are visiting frequently but not converting, use re-targeting ads. Additionally, in-platform notifications about deals, restocks, or new products can enhance conversion.</p></li>
</ol>
<hr>
</section>
</section>
</section>
<section id="future-works" class="level2">
<h2 class="anchored" data-anchor-id="future-works">Future Works</h2>
<section id="campaign-acceptance-acceptedcmp1-4-how-customer-responses-to-different-campaigns-correlate-with-campaign-succes" class="level4">
<h4 class="anchored" data-anchor-id="campaign-acceptance-acceptedcmp1-4-how-customer-responses-to-different-campaigns-correlate-with-campaign-succes">Campaign Acceptance (AcceptedCmp1-4): How customer responses to different campaigns correlate with campaign succes</h4>
</section>
<section id="interaction-with-the-company-numcatalogpurchases-customer_tenure-how-a-customers-history-with-the-company-influences-their-response-to-campaigns." class="level4">
<h4 class="anchored" data-anchor-id="interaction-with-the-company-numcatalogpurchases-customer_tenure-how-a-customers-history-with-the-company-influences-their-response-to-campaigns.">Interaction with the Company (NumCatalogPurchases, Customer_Tenure): How a customer’s history with the company influences their response to campaigns.</h4>
</section>
<section id="feature-selection" class="level3">
<h3 class="anchored" data-anchor-id="feature-selection">Feature Selection</h3>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>